/**
 * 示例词库：人教版七年级上册（Starter Units + Unit 1-4）
 * 每行：[单元, 单词, 音标, 词性, 中文释义, 例句, 例句翻译]
 */
(function () {
  const book = {
    key: 'g7a',
    name: '示例词库-人教版七年级上册',
    file: '示例词库-人教版七年级上册.xlsx',
    words: [
      // Starter Unit 1 Hello!
      ['Starter Unit 1', 'good', '/ɡʊd/', 'adj.', '好的', 'Good morning!', '早上好！'],
      ['Starter Unit 1', 'morning', '/ˈmɔːnɪŋ/', 'n.', '早晨；上午', 'Good morning!', '早上好！'],
      ['Starter Unit 1', 'hi', '/haɪ/', 'interj.', '嗨；喂', 'Hi, Alice!', '嗨，艾丽斯！'],
      ['Starter Unit 1', 'hello', '/həˈləʊ/', 'interj.', '你好；喂', 'Hello, Frank!', '你好，弗兰克！'],
      ['Starter Unit 1', 'afternoon', '/ˌɑːftəˈnuːn/', 'n.', '下午', 'Good afternoon!', '下午好！'],
      ['Starter Unit 1', 'evening', '/ˈiːvnɪŋ/', 'n.', '晚上；傍晚', 'Good evening!', '晚上好！'],
      ['Starter Unit 1', 'how', '/haʊ/', 'adv.', '怎样；如何', 'How are you?', '你好吗？'],
      ['Starter Unit 1', 'are', '/ɑː(r)/', 'v.', '是', 'How are you?', '你好吗？'],
      ['Starter Unit 1', 'you', '/juː/', 'pron.', '你；你们', 'How are you?', '你好吗？'],
      ['Starter Unit 1', 'I', '/aɪ/', 'pron.', '我', 'I am fine.', '我很好。'],
      ['Starter Unit 1', 'am', '/æm/', 'v.', '是', 'I am OK.', '我还好。'],
      ['Starter Unit 1', 'fine', '/faɪn/', 'adj.', '健康的；美好的', 'I am fine, thanks.', '我很好，谢谢。'],
      ['Starter Unit 1', 'thanks', '/θæŋks/', 'interj.', '感谢；谢谢', 'Fine, thanks.', '很好，谢谢。'],
      ['Starter Unit 1', 'OK', '/ˌəʊˈkeɪ/', 'adj.&adv.', '好；不错', 'I am OK.', '我还好。'],
      // Starter Unit 2 Keep Tidy!
      ['Starter Unit 2', 'what', '/wɒt/', 'pron.', '什么', 'What is this?', '这是什么？'],
      ['Starter Unit 2', 'is', '/ɪz/', 'v.', '是', 'What is it?', '它是什么？'],
      ['Starter Unit 2', 'this', '/ðɪs/', 'pron.', '这；这个', 'What is this?', '这是什么？'],
      ['Starter Unit 2', 'in', '/ɪn/', 'prep.', '用；以；在……里', 'What is this in English?', '这个用英语怎么说？'],
      ['Starter Unit 2', 'English', '/ˈɪŋɡlɪʃ/', 'n.', '英语', 'What is this in English?', '这个用英语怎么说？'],
      ['Starter Unit 2', 'map', '/mæp/', 'n.', '地图', 'It is a map.', '它是一张地图。'],
      ['Starter Unit 2', 'cup', '/kʌp/', 'n.', '杯子', 'This is a cup.', '这是一个杯子。'],
      ['Starter Unit 2', 'ruler', '/ˈruːlə(r)/', 'n.', '尺；直尺', 'That is a ruler.', '那是一把尺子。'],
      ['Starter Unit 2', 'pen', '/pen/', 'n.', '笔；钢笔', 'It is a pen.', '它是一支钢笔。'],
      ['Starter Unit 2', 'orange', '/ˈɒrɪndʒ/', 'n.', '橙子', 'It is an orange.', '它是一个橙子。'],
      ['Starter Unit 2', 'jacket', '/ˈdʒækɪt/', 'n.', '夹克衫', 'This is a jacket.', '这是一件夹克衫。'],
      ['Starter Unit 2', 'key', '/kiː/', 'n.', '钥匙', 'That is a key.', '那是一把钥匙。'],
      ['Starter Unit 2', 'it', '/ɪt/', 'pron.', '它', 'It is a quilt.', '它是一床被子。'],
      ['Starter Unit 2', 'a', '/ə/', 'art.', '一（人、事、物）', 'It is a map.', '它是一张地图。'],
      ['Starter Unit 2', 'that', '/ðæt/', 'pron.', '那；那个', 'What is that?', '那是什么？'],
      ['Starter Unit 2', 'spell', '/spel/', 'v.', '拼写', 'How do you spell it?', '你怎么拼写它？'],
      // Starter Unit 3 Welcome!
      ['Starter Unit 3', 'color', '/ˈkʌlə(r)/', 'n.', '颜色', 'What color is it?', '它是什么颜色的？'],
      ['Starter Unit 3', 'red', '/red/', 'adj.&n.', '红色（的）', 'It is red.', '它是红色的。'],
      ['Starter Unit 3', 'yellow', '/ˈjeləʊ/', 'adj.&n.', '黄色（的）', 'The key is yellow.', '钥匙是黄色的。'],
      ['Starter Unit 3', 'green', '/ɡriːn/', 'adj.&n.', '绿色（的）', 'The cup is green.', '杯子是绿色的。'],
      ['Starter Unit 3', 'blue', '/bluː/', 'adj.&n.', '蓝色（的）', 'The pen is blue.', '钢笔是蓝色的。'],
      ['Starter Unit 3', 'black', '/blæk/', 'adj.&n.', '黑色（的）', 'It is black and white.', '它是黑白相间的。'],
      ['Starter Unit 3', 'white', '/waɪt/', 'adj.&n.', '白色（的）', 'It is black and white.', '它是黑白相间的。'],
      ['Starter Unit 3', 'purple', '/ˈpɜːpl/', 'adj.&n.', '紫色（的）', 'The jacket is purple.', '夹克衫是紫色的。'],
      ['Starter Unit 3', 'brown', '/braʊn/', 'adj.&n.', '棕色（的）；褐色（的）', 'The ruler is brown.', '尺子是棕色的。'],
      ['Starter Unit 3', 'the', '/ðə/', 'art.', '指已提到或易领会到的人或事物', 'The key is yellow.', '钥匙是黄色的。'],
      ['Starter Unit 3', 'now', '/naʊ/', 'adv.', '现在；目前', 'Now you see it.', '现在你看到它了。'],
      ['Starter Unit 3', 'see', '/siː/', 'v.', '理解；明白', 'I see.', '我明白了。'],
      ['Starter Unit 3', 'can', '/kæn/', 'modal v.', '能；会', 'I can say it.', '我会说它。'],
      ['Starter Unit 3', 'say', '/seɪ/', 'v.', '说；讲', 'Say it in English.', '用英语说它。'],
      // Unit 1 You and Me
      ['Unit 1', 'name', '/neɪm/', 'n.', '名字；名称', 'My name is Gina.', '我的名字叫吉娜。'],
      ['Unit 1', 'nice', '/naɪs/', 'adj.', '令人愉快的；宜人的', 'Nice to meet you!', '很高兴见到你！'],
      ['Unit 1', 'to', '/tuː/', 'part.', '用于某些动词、形容词后', 'Nice to meet you.', '很高兴见到你。'],
      ['Unit 1', 'meet', '/miːt/', 'v.', '遇见；相逢', 'Nice to meet you!', '很高兴见到你！'],
      ['Unit 1', 'too', '/tuː/', 'adv.', '也；又；太', 'Nice to meet you, too.', '见到你我也很高兴。'],
      ['Unit 1', 'your', '/jɔː(r)/', 'pron.', '你的；你们的', 'What is your name?', '你叫什么名字？'],
      ['Unit 1', 'my', '/maɪ/', 'pron.', '我的', 'My name is Alan.', '我的名字叫艾伦。'],
      ['Unit 1', 'his', '/hɪz/', 'pron.', '他的', 'His name is Mike.', '他的名字叫迈克。'],
      ['Unit 1', 'her', '/hɜː(r)/', 'pron.', '她的', 'Her name is Jenny.', '她的名字叫珍妮。'],
      ['Unit 1', 'yes', '/jes/', 'interj.', '是的；可以', 'Yes, I am.', '是的，我是。'],
      ['Unit 1', 'no', '/nəʊ/', 'interj.', '不；没有；不是', 'No, I am not.', '不，我不是。'],
      ['Unit 1', 'she', '/ʃiː/', 'pron.', '她', 'She is Mary.', '她是玛丽。'],
      ['Unit 1', 'he', '/hiː/', 'pron.', '他', 'He is Jack.', '他是杰克。'],
      ['Unit 1', 'we', '/wiː/', 'pron.', '我们', 'We are students.', '我们是学生。'],
      ['Unit 1', 'number', '/ˈnʌmbə(r)/', 'n.', '号码；数字', 'What is your phone number?', '你的电话号码是多少？'],
      ['Unit 1', 'phone', '/fəʊn/', 'n.', '电话；电话机', 'My phone number is 555.', '我的电话号码是555。'],
      ['Unit 1', 'telephone', '/ˈtelɪfəʊn/', 'n.', '电话；电话机', 'His telephone is red.', '他的电话是红色的。'],
      ['Unit 1', 'first', '/fɜːst/', 'adj.', '第一', 'Her first name is Linda.', '她的名字是琳达。'],
      ['Unit 1', 'last', '/lɑːst/', 'adj.', '最后的；末尾的', 'My last name is Green.', '我姓格林。'],
      ['Unit 1', 'friend', '/frend/', 'n.', '朋友', 'She is my friend.', '她是我的朋友。'],
      ['Unit 1', 'China', '/ˈtʃaɪnə/', 'n.', '中国', 'I am in China.', '我在中国。'],
      ['Unit 1', 'middle', '/ˈmɪdl/', 'adj.', '中间的', 'She is in a middle school.', '她在一所中学。'],
      ['Unit 1', 'school', '/skuːl/', 'n.', '学校', 'This is my school.', '这是我的学校。'],
      // Unit 2 We're Family!
      ['Unit 2', 'family', '/ˈfæməli/', 'n.', '家；家庭', 'This is my family.', '这是我的家庭。'],
      ['Unit 2', 'father', '/ˈfɑːðə(r)/', 'n.', '父亲；爸爸', 'My father is a teacher.', '我的爸爸是一位老师。'],
      ['Unit 2', 'mother', '/ˈmʌðə(r)/', 'n.', '母亲；妈妈', 'Her mother is fine.', '她的妈妈很好。'],
      ['Unit 2', 'brother', '/ˈbrʌðə(r)/', 'n.', '兄；弟', 'That is my brother.', '那是我的弟弟。'],
      ['Unit 2', 'sister', '/ˈsɪstə(r)/', 'n.', '姐；妹', 'My sister is nine.', '我的妹妹九岁。'],
      ['Unit 2', 'grandfather', '/ˈɡrænfɑːðə(r)/', 'n.', '祖父；外祖父', 'His grandfather is here.', '他的爷爷在这里。'],
      ['Unit 2', 'grandmother', '/ˈɡrænmʌðə(r)/', 'n.', '祖母；外祖母', 'My grandmother is kind.', '我的奶奶很和蔼。'],
      ['Unit 2', 'grandparent', '/ˈɡrænpeərənt/', 'n.', '祖父（母）；外祖父（母）', 'My grandparents are at home.', '我的祖父母在家。'],
      ['Unit 2', 'parent', '/ˈpeərənt/', 'n.', '父（母）亲', 'Her parents are teachers.', '她的父母是老师。'],
      ['Unit 2', 'son', '/sʌn/', 'n.', '儿子', 'Their son is Tom.', '他们的儿子是汤姆。'],
      ['Unit 2', 'daughter', '/ˈdɔːtə(r)/', 'n.', '女儿', 'His daughter is cute.', '他的女儿很可爱。'],
      ['Unit 2', 'uncle', '/ˈʌŋkl/', 'n.', '舅父；叔父；伯父；姑父；姨父', 'My uncle is tall.', '我的叔叔很高。'],
      ['Unit 2', 'aunt', '/ɑːnt/', 'n.', '姑母；姨母；伯母；婶母；舅母', 'Her aunt is a doctor.', '她的姑姑是医生。'],
      ['Unit 2', 'cousin', '/ˈkʌzn/', 'n.', '堂兄（弟、姐、妹）；表兄（弟、姐、妹）', 'He is my cousin.', '他是我的表兄。'],
      ['Unit 2', 'who', '/huː/', 'pron.', '谁；什么人', 'Who is she?', '她是谁？'],
      ['Unit 2', 'they', '/ðeɪ/', 'pron.', '他（她、它）们', 'They are my parents.', '他们是我的父母。'],
      ['Unit 2', 'these', '/ðiːz/', 'pron.', '这些', 'These are my friends.', '这些是我的朋友。'],
      ['Unit 2', 'those', '/ðəʊz/', 'pron.', '那些', 'Those are apples.', '那些是苹果。'],
      ['Unit 2', 'photo', '/ˈfəʊtəʊ/', 'n.', '照片', 'Here is a photo of my family.', '这是一张我的全家福。'],
      ['Unit 2', 'have', '/hæv/', 'v.', '经受；经历；有', 'I have a happy family.', '我有一个幸福的家庭。'],
      ['Unit 2', 'day', '/deɪ/', 'n.', '一天；一日；白天', 'Have a good day!', '祝你过得愉快！'],
      ['Unit 2', 'love', '/lʌv/', 'v.&n.', '爱；喜爱', 'I love my family.', '我爱我的家人。'],
      // Unit 3 My School
      ['Unit 3', 'book', '/bʊk/', 'n.', '书', 'This is my book.', '这是我的书。'],
      ['Unit 3', 'pencil', '/ˈpensl/', 'n.', '铅笔', 'Is this your pencil?', '这是你的铅笔吗？'],
      ['Unit 3', 'eraser', '/ɪˈreɪzə(r)/', 'n.', '橡皮', 'The eraser is white.', '橡皮是白色的。'],
      ['Unit 3', 'box', '/bɒks/', 'n.', '箱；盒', 'My pencil box is blue.', '我的铅笔盒是蓝色的。'],
      ['Unit 3', 'schoolbag', '/ˈskuːlbæɡ/', 'n.', '书包', 'Her schoolbag is heavy.', '她的书包很重。'],
      ['Unit 3', 'dictionary', '/ˈdɪkʃənri/', 'n.', '词典；字典', 'I have a dictionary.', '我有一本词典。'],
      ['Unit 3', 'notebook', '/ˈnəʊtbʊk/', 'n.', '笔记本', 'This notebook is new.', '这本笔记本是新的。'],
      ['Unit 3', 'bag', '/bæɡ/', 'n.', '包；袋', 'Your bag is on the desk.', '你的包在书桌上。'],
      ['Unit 3', 'watch', '/wɒtʃ/', 'n.', '表；手表', 'His watch is black.', '他的手表是黑色的。'],
      ['Unit 3', 'computer', '/kəmˈpjuːtə(r)/', 'n.', '计算机；电脑', 'The computer is in the classroom.', '电脑在教室里。'],
      ['Unit 3', 'game', '/ɡeɪm/', 'n.', '游戏；运动；比赛', 'Is that a computer game?', '那是一个电脑游戏吗？'],
      ['Unit 3', 'card', '/kɑːd/', 'n.', '卡片', 'Here is my ID card.', '这是我的身份证。'],
      ['Unit 3', 'library', '/ˈlaɪbrəri/', 'n.', '图书馆', 'I read books in the library.', '我在图书馆看书。'],
      ['Unit 3', 'classroom', '/ˈklɑːsruːm/', 'n.', '教室', 'Our classroom is big.', '我们的教室很大。'],
      ['Unit 3', 'e-mail', '/ˈiːmeɪl/', 'n.', '电子邮件', 'Please e-mail me.', '请给我发电子邮件。'],
      ['Unit 3', 'at', '/æt/', 'prep.', '在（某处、某时间）', 'E-mail me at 123@qq.com.', '发邮件到123@qq.com给我。'],
      ['Unit 3', 'call', '/kɔːl/', 'v.', '（给……）打电话', 'Call me at 685.', '打685找我。'],
      ['Unit 3', 'lost', '/lɒst/', 'v.', '遗失；丢失', 'I lost my pen.', '我丢了钢笔。'],
      ['Unit 3', 'found', '/faʊnd/', 'v.', '找到；发现', 'I found a key.', '我找到了一把钥匙。'],
      ['Unit 3', 'some', '/sʌm/', 'adj.', '一些；某些', 'Some books are on the desk.', '一些书在书桌上。'],
      ['Unit 3', 'help', '/help/', 'v.&n.', '帮助；援助', 'Can you help me?', '你能帮我吗？'],
      ['Unit 3', 'ask', '/ɑːsk/', 'v.', '请求；要求；询问', 'Ask the teacher for it.', '去找老师要它。'],
      ['Unit 3', 'thank', '/θæŋk/', 'v.', '感谢；谢谢', 'Thank you for your help.', '谢谢你的帮助。'],
      ['Unit 3', 'welcome', '/ˈwelkəm/', 'adj.', '受欢迎的', 'You are welcome.', '不客气。'],
      // Unit 4 My Favourite Subject
      ['Unit 4', 'subject', '/ˈsʌbdʒɪkt/', 'n.', '学科；科目', 'What is your favourite subject?', '你最喜欢的学科是什么？'],
      ['Unit 4', 'favorite', '/ˈfeɪvərɪt/', 'adj.&n.', '特别喜爱的（人或事物）', 'English is my favorite.', '英语是我的最爱。'],
      ['Unit 4', 'science', '/ˈsaɪəns/', 'n.', '科学', 'I like science.', '我喜欢科学。'],
      ['Unit 4', 'math', '/mæθ/', 'n.', '数学', 'Math is difficult for me.', '数学对我来说很难。'],
      ['Unit 4', 'P.E.', '/ˌpiː ˈiː/', 'n.', '体育', 'We have P.E. on Monday.', '我们星期一上体育课。'],
      ['Unit 4', 'music', '/ˈmjuːzɪk/', 'n.', '音乐；乐曲', 'Music is relaxing.', '音乐令人放松。'],
      ['Unit 4', 'art', '/ɑːt/', 'n.', '艺术；美术', 'Her art class is fun.', '她的美术课很有趣。'],
      ['Unit 4', 'history', '/ˈhɪstri/', 'n.', '历史', 'History is on Tuesday.', '历史课在星期二。'],
      ['Unit 4', 'why', '/waɪ/', 'adv.', '为什么', 'Why do you like English?', '你为什么喜欢英语？'],
      ['Unit 4', 'because', '/bɪˈkɒz/', 'conj.', '因为', 'Because it is interesting.', '因为它很有趣。'],
      ['Unit 4', 'interesting', '/ˈɪntrəstɪŋ/', 'adj.', '有趣的', 'The book is interesting.', '这本书很有趣。'],
      ['Unit 4', 'fun', '/fʌn/', 'adj.', '有趣的；使人快乐的', 'The game is fun.', '这个游戏很有趣。'],
      ['Unit 4', 'boring', '/ˈbɔːrɪŋ/', 'adj.', '无聊的；令人生厌的', 'The film is boring.', '这部电影很无聊。'],
      ['Unit 4', 'relaxing', '/rɪˈlæksɪŋ/', 'adj.', '令人放松的', 'Music is relaxing.', '音乐令人放松。'],
      ['Unit 4', 'difficult', '/ˈdɪfɪkəlt/', 'adj.', '困难的', 'Math is difficult.', '数学很难。'],
      ['Unit 4', 'easy', '/ˈiːzi/', 'adj.', '容易的；不费力的', 'The question is easy.', '这个问题很简单。'],
      ['Unit 4', 'Monday', '/ˈmʌndeɪ/', 'n.', '星期一', 'Today is Monday.', '今天是星期一。'],
      ['Unit 4', 'Friday', '/ˈfraɪdeɪ/', 'n.', '星期五', 'We have art on Friday.', '我们星期五上美术课。'],
      ['Unit 4', 'teacher', '/ˈtiːtʃə(r)/', 'n.', '教师；老师', 'Our teacher is kind.', '我们的老师很和蔼。'],
      ['Unit 4', 'class', '/klɑːs/', 'n.', '班级；课', 'My favorite class is English.', '我最喜欢的课是英语。'],
      ['Unit 4', 'hour', '/ˈaʊə(r)/', 'n.', '小时', 'The class is one hour long.', '这节课一小时长。'],
      ['Unit 4', 'useful', '/ˈjuːsfl/', 'adj.', '有用的；有益的', 'English is useful.', '英语很有用。'],
      ['Unit 4', 'from', '/frɒm/', 'prep.', '从……开始', 'From Monday to Friday.', '从星期一到星期五。'],
      ['Unit 4', 'finish', '/ˈfɪnɪʃ/', 'v.', '完成；做好', 'Class finishes at four.', '课在四点结束。'],
      ['Unit 4', 'lesson', '/ˈlesn/', 'n.', '课；一节课', 'We have five lessons today.', '我们今天有五节课。'],
    ],
  };
  if (typeof window !== 'undefined') {
    window.VocabSampleBooks = window.VocabSampleBooks || [];
    window.VocabSampleBooks.push(book);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = book;
})();
