/**
 * 示例词库：人教版八年级上册（Unit 1-10）
 * 每行：[单元, 单词, 音标, 词性, 中文释义, 例句, 例句翻译]
 */
(function () {
  const book = {
    key: 'g8a',
    name: '示例词库-人教版八年级上册',
    file: '示例词库-人教版八年级上册.xlsx',
    words: [
      // Unit 1 Where did you go on vacation?
      ['Unit 1', 'anyone', '/ˈeniwʌn/', 'pron.', '任何人', 'Did anyone come to see me?', '有人来看我吗？'],
      ['Unit 1', 'anywhere', '/ˈeniweə(r)/', 'adv.', '任何地方', 'I can not find my key anywhere.', '我哪儿都找不到我的钥匙。'],
      ['Unit 1', 'wonderful', '/ˈwʌndəfl/', 'adj.', '精彩的；绝妙的', 'We had a wonderful time.', '我们玩得很开心。'],
      ['Unit 1', 'few', '/fjuː/', 'adj.&pron.', '不多；很少', 'Few people know the answer.', '很少有人知道答案。'],
      ['Unit 1', 'quite a few', '', 'phr.', '相当多；不少', 'Quite a few students are late.', '相当多的学生迟到了。'],
      ['Unit 1', 'most', '/məʊst/', 'adj.&adv.', '最多；大多数', 'Most of us like English.', '我们大多数人喜欢英语。'],
      ['Unit 1', 'something', '/ˈsʌmθɪŋ/', 'pron.', '某事；某物', 'I have something to tell you.', '我有件事要告诉你。'],
      ['Unit 1', 'nothing', '/ˈnʌθɪŋ/', 'pron.', '没有什么；没有一件东西', 'There is nothing in the box.', '盒子里什么也没有。'],
      ['Unit 1', 'myself', '/maɪˈself/', 'pron.', '我自己', 'I did it myself.', '我自己做的。'],
      ['Unit 1', 'everyone', '/ˈevriwʌn/', 'pron.', '每人；人人；所有人', 'Everyone is here today.', '今天大家都到了。'],
      ['Unit 1', 'yourself', '/jɔːˈself/', 'pron.', '你自己；您自己', 'Did you hurt yourself?', '你伤到自己了吗？'],
      ['Unit 1', 'hen', '/hen/', 'n.', '母鸡', 'The hen lays eggs every day.', '母鸡每天下蛋。'],
      ['Unit 1', 'pig', '/pɪɡ/', 'n.', '猪', 'The pig is very fat.', '这头猪很肥。'],
      ['Unit 1', 'seem', '/siːm/', 'v.', '好像；似乎；看来', 'She seems happy today.', '她今天好像很高兴。'],
      ['Unit 1', 'bored', '/bɔːd/', 'adj.', '厌倦的；烦闷的', 'I feel bored at home.', '我在家觉得很无聊。'],
      ['Unit 1', 'diary', '/ˈdaɪəri/', 'n.', '日记；日记簿', 'I keep a diary every day.', '我每天记日记。'],
      ['Unit 1', 'activity', '/ækˈtɪvəti/', 'n.', '活动', 'We have many after-school activities.', '我们有很多课外活动。'],
      ['Unit 1', 'decide', '/dɪˈsaɪd/', 'v.', '决定；选定', 'I decide to study hard.', '我决定努力学习。'],
      ['Unit 1', 'try', '/traɪ/', 'v.&n.', '尝试；设法；努力', 'Try your best and you will win.', '尽你最大努力，你会赢的。'],
      ['Unit 1', 'bird', '/bɜːd/', 'n.', '鸟', 'The bird can sing beautifully.', '这只鸟唱歌很好听。'],
      ['Unit 1', 'bicycle', '/ˈbaɪsɪkl/', 'n.', '自行车；脚踏车', 'I ride a bicycle to school.', '我骑自行车上学。'],
      ['Unit 1', 'building', '/ˈbɪldɪŋ/', 'n.', '建筑物；房子', 'That building is very tall.', '那栋楼很高。'],
      ['Unit 1', 'trader', '/ˈtreɪdə(r)/', 'n.', '商人', 'The trader sells tea and coffee.', '这个商人卖茶叶和咖啡。'],
      ['Unit 1', 'wonder', '/ˈwʌndə(r)/', 'v.', '想知道；琢磨', 'I wonder where he is now.', '我想知道他现在在哪儿。'],
      ['Unit 1', 'difference', '/ˈdɪfrəns/', 'n.', '差别；差异', 'What is the difference between them?', '它们之间有什么区别？'],
      ['Unit 1', 'top', '/tɒp/', 'n.', '顶部；表面', 'We climbed to the top of the hill.', '我们爬到了山顶。'],
      ['Unit 1', 'wait', '/weɪt/', 'v.', '等待；等候', 'Wait for me, please.', '请等等我。'],
      ['Unit 1', 'umbrella', '/ʌmˈbrelə/', 'n.', '伞；雨伞', 'Take an umbrella with you.', '带把伞吧。'],
      ['Unit 1', 'wet', '/wet/', 'adj.', '湿的；潮湿的；下雨的', 'My clothes are wet in the rain.', '我的衣服在雨中淋湿了。'],
      ['Unit 1', 'because of', '', 'phr.', '因为', 'We stayed at home because of the rain.', '因为下雨，我们待在家里。'],
      ['Unit 1', 'below', '/bɪˈləʊ/', 'prep.&adv.', '在……下面；到……下面', 'The temperature is below zero.', '气温在零度以下。'],
      ['Unit 1', 'enough', '/ɪˈnʌf/', 'adj.&adv.', '足够的（地）；充分的（地）', 'We have enough food for the trip.', '我们有足够的食物去旅行。'],
      ['Unit 1', 'hungry', '/ˈhʌŋɡri/', 'adj.', '饥饿的', 'I am hungry after the game.', '比赛后我饿了。'],
      ['Unit 1', 'as', '/æz/', 'adv.', '像……一样；如同', 'He is as tall as me.', '他和我一样高。'],
      ['Unit 1', 'hill', '/hɪl/', 'n.', '小山；山丘', 'There is a small house on the hill.', '山上有一座小房子。'],
      ['Unit 1', 'duck', '/dʌk/', 'n.', '鸭', 'The ducks are swimming in the river.', '鸭子在河里游泳。'],
      ['Unit 1', 'dislike', '/dɪsˈlaɪk/', 'v.&n.', '不喜爱（的事物）；厌恶', 'I dislike rainy days.', '我不喜欢下雨天。'],
      // Unit 2 How often do you exercise?
      ['Unit 2', 'housework', '/ˈhaʊswɜːk/', 'n.', '家务劳动；家务事', 'I help with housework on weekends.', '我周末帮忙做家务。'],
      ['Unit 2', 'hardly', '/ˈhɑːdli/', 'adv.', '几乎不；几乎没有', 'He hardly ever watches TV.', '他几乎不看电视。'],
      ['Unit 2', 'ever', '/ˈevə(r)/', 'adv.', '在任何时候；曾经', 'Have you ever been to Beijing?', '你去过北京吗？'],
      ['Unit 2', 'once', '/wʌns/', 'adv.', '一次；曾经', 'I go there once a week.', '我一周去一次。'],
      ['Unit 2', 'twice', '/twaɪs/', 'adv.', '两次；两倍', 'I read English twice a day.', '我一天读两次英语。'],
      ['Unit 2', 'Internet', '/ˈɪntənet/', 'n.', '（国际）互联网；因特网', 'I surf the Internet on weekends.', '我周末上网。'],
      ['Unit 2', 'program', '/ˈprəʊɡræm/', 'n.', '节目', 'This TV program is interesting.', '这个电视节目很有趣。'],
      ['Unit 2', 'full', '/fʊl/', 'adj.', '忙的；满的；充满的', 'My week is full of activities.', '我这一周活动排得满满的。'],
      ['Unit 2', 'maybe', '/ˈmeɪbi/', 'adv.', '大概；或许；可能', 'Maybe he is at home.', '也许他在家。'],
      ['Unit 2', 'swing', '/swɪŋ/', 'n.', '秋千；摆动', 'The children are playing on the swing.', '孩子们在荡秋千。'],
      ['Unit 2', 'hardly ever', '', 'phr.', '几乎从不', 'I hardly ever eat junk food.', '我几乎从不吃垃圾食品。'],
      ['Unit 2', 'swing dance', '', 'phr.', '摇摆舞', 'She learns swing dance after school.', '她放学后学摇摆舞。'],
      ['Unit 2', 'stay up late', '', 'phr.', '熬夜；深夜不睡', 'Do not stay up late before exams.', '考试前不要熬夜。'],
      ['Unit 2', 'at least', '', 'phr.', '至少；不少于；起码', 'Sleep at least eight hours a day.', '每天至少睡八个小时。'],
      ['Unit 2', 'junk', '/dʒʌŋk/', 'n.', '垃圾；废旧杂物', 'Junk food is bad for health.', '垃圾食品对健康有害。'],
      ['Unit 2', 'coffee', '/ˈkɒfi/', 'n.', '咖啡', 'My father drinks coffee every morning.', '我爸爸每天早上喝咖啡。'],
      ['Unit 2', 'health', '/helθ/', 'n.', '健康；人的身体（或精神）状态', 'Walking is good for your health.', '散步对你的健康有益。'],
      ['Unit 2', 'result', '/rɪˈzʌlt/', 'n.', '结果；后果', 'The result of the game is great.', '比赛的结果很棒。'],
      ['Unit 2', 'although', '/ɔːlˈðəʊ/', 'conj.', '虽然；尽管；即使', 'Although he is young, he knows a lot.', '虽然他年纪小，但他懂得很多。'],
      ['Unit 2', 'through', '/θruː/', 'prep.', '以；凭借；穿过', 'We learn English through reading.', '我们通过阅读学习英语。'],
      ['Unit 2', 'mind', '/maɪnd/', 'n.', '头脑；心智', 'Reading opens the mind.', '阅读开阔心智。'],
      ['Unit 2', 'body', '/ˈbɒdi/', 'n.', '身体', 'Exercise makes the body strong.', '锻炼使身体强壮。'],
      ['Unit 2', 'such', '/sʌtʃ/', 'adj.&pron.', '这样的；那样的；类似的', 'I like such books very much.', '我非常喜欢这样的书。'],
      ['Unit 2', 'together', '/təˈɡeðə(r)/', 'adv.', '在一起；共同', 'We study together after class.', '我们课后一起学习。'],
      ['Unit 2', 'however', '/haʊˈevə(r)/', 'adv.', '然而；不过', 'It was raining; however, we went out.', '天在下雨，然而我们还是出去了。'],
      ['Unit 2', 'almost', '/ˈɔːlməʊst/', 'adv.', '几乎；差不多', 'Almost everyone likes the song.', '几乎每个人都喜欢这首歌。'],
      ['Unit 2', 'none', '/nʌn/', 'pron.', '没有一个；毫无', 'None of the answers is right.', '没有一个答案是对的。'],
      ['Unit 2', 'less', '/les/', 'adv.&adj.', '较少（的）；更少（的）', 'You should eat less meat.', '你应该少吃点肉。'],
      ['Unit 2', 'point', '/pɔɪnt/', 'n.', '得分；点；看法', 'What is your point?', '你的看法是什么？'],
      // Unit 3 I'm more outgoing than my sister.
      ['Unit 3', 'outgoing', '/ˈaʊtɡəʊɪŋ/', 'adj.', '爱交际的；友好的；外向的', 'My sister is more outgoing than me.', '我姐姐比我更外向。'],
      ['Unit 3', 'both', '/bəʊθ/', 'adj.&pron.', '两个；两个都', 'Both of them are good students.', '他们两个都是好学生。'],
      ['Unit 3', 'talented', '/ˈtæləntɪd/', 'adj.', '有才能的；有才干的', 'She is talented in music.', '她在音乐方面有天赋。'],
      ['Unit 3', 'truly', '/ˈtruːli/', 'adv.', '真正；确实', 'I truly believe you can do it.', '我真的相信你能做到。'],
      ['Unit 3', 'care', '/keə(r)/', 'v.', '在意；担忧；关心', 'She cares about her friends.', '她关心她的朋友。'],
      ['Unit 3', 'serious', '/ˈsɪəriəs/', 'adj.', '严肃的；稳重的', 'Our math teacher is very serious.', '我们的数学老师很严肃。'],
      ['Unit 3', 'mirror', '/ˈmɪrə(r)/', 'n.', '镜子', 'She is looking at herself in the mirror.', '她正在照镜子。'],
      ['Unit 3', 'necessary', '/ˈnesəsəri/', 'adj.', '必需的；必要的', 'It is necessary to learn English well.', '学好英语是必要的。'],
      ['Unit 3', 'should', '/ʃʊd/', 'modal v.', '应该；应当；可以', 'You should help your parents.', '你应该帮助你的父母。'],
      ['Unit 3', 'touch', '/tʌtʃ/', 'v.', '触摸；接触', 'Do not touch the wet paint.', '不要碰未干的油漆。'],
      ['Unit 3', 'reach', '/riːtʃ/', 'v.', '到达；伸手；达到', 'We reached the village at noon.', '我们中午到达了村庄。'],
      ['Unit 3', 'brave', '/breɪv/', 'adj.', '勇敢的；无畏的', 'The brave boy saved the cat.', '那个勇敢的男孩救了那只猫。'],
      ['Unit 3', 'sense', '/sens/', 'n.', '感觉；意识；观念', 'He has a good sense of humor.', '他很有幽默感。'],
      ['Unit 3', 'humor', '/ˈhjuːmə(r)/', 'n.', '幽默；幽默感', 'His stories are full of humor.', '他的故事充满幽默。'],
      ['Unit 3', 'besides', '/bɪˈsaɪdz/', 'prep.', '除……之外（还）', 'Besides English, I like music.', '除了英语，我还喜欢音乐。'],
      ['Unit 3', 'hard-working', '/ˌhɑːd ˈwɜːkɪŋ/', 'adj.', '工作努力的；辛勤的', 'He is a hard-working student.', '他是一个勤奋的学生。'],
      ['Unit 3', 'competition', '/ˌkɒmpəˈtɪʃn/', 'n.', '比赛；竞赛；竞争', 'She won the singing competition.', '她赢得了歌唱比赛。'],
      ['Unit 3', 'fantastic', '/fænˈtæstɪk/', 'adj.', '极好的；了不起的', 'The film is fantastic.', '这部电影太棒了。'],
      ['Unit 3', 'primary', '/ˈpraɪməri/', 'adj.', '小学教育的；初级的', 'I met her in primary school.', '我在小学认识她。'],
      ['Unit 3', 'primary school', '', 'phr.', '小学', 'My little brother is in primary school.', '我弟弟在上小学。'],
      ['Unit 3', 'information', '/ˌɪnfəˈmeɪʃn/', 'n.', '信息；消息', 'Please give me more information.', '请给我更多信息。'],
      ['Unit 3', 'loudly', '/ˈlaʊdli/', 'adv.', '喧闹地；大声地', 'Do not talk loudly in the library.', '不要在图书馆大声说话。'],
      ['Unit 3', 'quietly', '/ˈkwaɪətli/', 'adv.', '轻声地；轻柔地；安静地', 'She closed the door quietly.', '她轻轻地关上门。'],
      ['Unit 3', 'clearly', '/ˈklɪəli/', 'adv.', '清楚地；清晰地；明白地', 'Please speak more clearly.', '请说得更清楚些。'],
      ['Unit 3', 'win', '/wɪn/', 'v.', '获胜；赢；赢得', 'Our team won the game.', '我们队赢得了比赛。'],
      ['Unit 3', 'though', '/ðəʊ/', 'adv.', '不过；可是；然而', 'It is hard work; I enjoy it, though.', '这是辛苦的工作，不过我很喜欢。'],
      ['Unit 3', 'fact', '/fækt/', 'n.', '现实；事实', 'Tell me the facts, please.', '请告诉我事实。'],
      ['Unit 3', 'break', '/breɪk/', 'n.', '（课间）休息；间歇', 'Let us take a short break.', '我们休息一会儿吧。'],
      ['Unit 3', 'laugh', '/lɑːf/', 'v.&n.', '笑；发笑', 'His joke made everyone laugh.', '他的笑话让大家都笑了。'],
      ['Unit 3', 'similar', '/ˈsɪmələ(r)/', 'adj.', '相像的；类似的', 'The two brothers look similar.', '这两兄弟长得很像。'],
      ['Unit 3', 'be similar to', '', 'phr.', '与……相像的、类似的', 'My bag is similar to yours.', '我的包和你的很像。'],
      // Unit 4 What's the best movie theater?
      ['Unit 4', 'theater', '/ˈθɪətə(r)/', 'n.', '剧场；电影院；戏院', 'There is a new theater near my home.', '我家附近有一家新电影院。'],
      ['Unit 4', 'comfortable', '/ˈkʌmftəbl/', 'adj.', '舒适的；使人舒服的', 'The seats in this cinema are comfortable.', '这家电影院的座位很舒服。'],
      ['Unit 4', 'seat', '/siːt/', 'n.', '座位；坐处', 'Please take a seat.', '请坐。'],
      ['Unit 4', 'screen', '/skriːn/', 'n.', '屏幕；银幕', 'The TV has a big screen.', '这台电视屏幕很大。'],
      ['Unit 4', 'close', '/kləʊs/', 'adj.', '（在空间、时间上）接近', 'The shop is close to our school.', '商店离我们学校很近。'],
      ['Unit 4', 'service', '/ˈsɜːvɪs/', 'n.', '接待；服务', 'The service in this hotel is good.', '这家酒店的服务很好。'],
      ['Unit 4', 'cheaply', '/ˈtʃiːpli/', 'adv.', '便宜地；低廉地', 'You can buy clothes cheaply here.', '你可以在这里便宜地买到衣服。'],
      ['Unit 4', 'song', '/sɒŋ/', 'n.', '歌；歌曲', 'She sings English songs well.', '她英文歌唱得很好。'],
      ['Unit 4', 'choose', '/tʃuːz/', 'v.', '选择；挑选', 'You can choose any book you like.', '你可以选任何你喜欢的书。'],
      ['Unit 4', 'carefully', '/ˈkeəfəli/', 'adv.', '细致地；小心地；谨慎地', 'Please listen carefully in class.', '上课请认真听讲。'],
      ['Unit 4', 'reporter', '/rɪˈpɔːtə(r)/', 'n.', '记者', 'The reporter is interviewing the star.', '记者正在采访那位明星。'],
      ['Unit 4', 'fresh', '/freʃ/', 'adj.', '新鲜的；清新的', 'The vegetables in the market are fresh.', '市场里的蔬菜很新鲜。'],
      ['Unit 4', 'comfortably', '/ˈkʌmftəbli/', 'adv.', '舒服地；舒适地', 'We sat comfortably on the sofa.', '我们舒服地坐在沙发上。'],
      ['Unit 4', 'worse', '/wɜːs/', 'adj.&adv.', '更差（的）；更坏（的）；更糟（的）', 'The weather is worse today.', '今天天气更糟。'],
      ['Unit 4', 'worst', '/wɜːst/', 'adj.&adv.', '最差（的）；最坏（的）；最糟（的）', 'This is the worst film of the year.', '这是今年最差的电影。'],
      ['Unit 4', 'cheap', '/tʃiːp/', 'adj.', '廉价的；便宜的', 'The shirt is cheap but nice.', '这件衬衫便宜但好看。'],
      ['Unit 4', 'crowded', '/ˈkraʊdɪd/', 'adj.', '人多的；拥挤的；挤满的', 'The bus is always crowded in the morning.', '早上公交车总是很挤。'],
      ['Unit 4', 'performer', '/pəˈfɔːmə(r)/', 'n.', '表演者；演员', 'The performers danced very well.', '演员们舞跳得很好。'],
      ['Unit 4', 'talent', '/ˈtælənt/', 'n.', '天资；天赋', 'She has a talent for drawing.', '她有绘画天赋。'],
      ['Unit 4', 'common', '/ˈkɒmən/', 'adj.', '普通的；常见的', 'Smith is a very common name.', '史密斯是一个很常见的名字。'],
      ['Unit 4', 'have ... in common', '', 'phr.', '有相同特征；（想法、兴趣等方面）相同', 'We have a lot in common.', '我们有很多共同点。'],
      ['Unit 4', 'beautifully', '/ˈbjuːtɪfli/', 'adv.', '美好地；漂亮地', 'She plays the piano beautifully.', '她钢琴弹得很优美。'],
      ['Unit 4', 'be up to', '', 'phr.', '是……的职责；由……决定', 'It is up to you to decide.', '由你来决定。'],
      ['Unit 4', 'role', '/rəʊl/', 'n.', '作用；职能；角色', 'He plays an important role in the team.', '他在队里起重要作用。'],
      ['Unit 4', 'play a role', '', 'phr.', '发挥作用；有影响', 'Everyone plays a role in the game.', '每个人在游戏中都有作用。'],
      ['Unit 4', 'winner', '/ˈwɪnə(r)/', 'n.', '获胜者；优胜者', 'The winner gets a big prize.', '获胜者得到一份大奖。'],
      ['Unit 4', 'prize', '/praɪz/', 'n.', '奖；奖品；奖金', 'She won first prize in the contest.', '她在比赛中获得一等奖。'],
      ['Unit 4', 'give away', '', 'phr.', '赠送；捐赠', 'They gave away books to the school.', '他们向学校捐赠了图书。'],
      ['Unit 4', 'seriously', '/ˈsɪəriəsli/', 'adv.', '严重地；严肃地；认真地', 'Take your homework seriously.', '认真对待你的作业。'],
      ['Unit 4', 'take ... seriously', '', 'phr.', '认真对待……', 'You should take the exam seriously.', '你应该认真对待这次考试。'],
      // Unit 5 Do you want to watch a game show?
      ['Unit 5', 'news', '/njuːz/', 'n.', '新闻节目；新闻', 'I watch the news every evening.', '我每天晚上看新闻。'],
      ['Unit 5', 'educational', '/ˌedʒuˈkeɪʃənl/', 'adj.', '教育的；有教育意义的', 'This is an educational movie.', '这是一部有教育意义的电影。'],
      ['Unit 5', 'plan', '/plæn/', 'v.&n.', '打算；计划', 'We plan to visit the museum.', '我们计划去参观博物馆。'],
      ['Unit 5', 'hope', '/həʊp/', 'v.&n.', '希望', 'I hope to see you soon.', '我希望很快见到你。'],
      ['Unit 5', 'discussion', '/dɪˈskʌʃn/', 'n.', '讨论；商量', 'We had a discussion about the plan.', '我们讨论了这个计划。'],
      ['Unit 5', 'happen', '/ˈhæpən/', 'v.', '发生；出现', 'What happened to your bike?', '你的自行车怎么了？'],
      ['Unit 5', 'may', '/meɪ/', 'modal v.', '也许；可能；可以', 'It may rain this afternoon.', '今天下午可能会下雨。'],
      ['Unit 5', 'expect', '/ɪkˈspekt/', 'v.', '预料；期待', 'I expect to hear from you.', '我期待收到你的来信。'],
      ['Unit 5', 'comedy', '/ˈkɒmədi/', 'n.', '喜剧；喜剧片', 'This comedy makes me laugh.', '这部喜剧让我大笑。'],
      ['Unit 5', 'cartoon', '/kɑːˈtuːn/', 'n.', '卡通片；动画片', 'Children like watching cartoons.', '孩子们喜欢看动画片。'],
      ['Unit 5', 'famous', '/ˈfeɪməs/', 'adj.', '著名的；出名的', 'Beijing is famous for the Great Wall.', '北京以长城闻名。'],
      ['Unit 5', 'appear', '/əˈpɪə(r)/', 'v.', '出现', 'A rainbow appeared in the sky.', '天空中出现了一道彩虹。'],
      ['Unit 5', 'become', '/bɪˈkʌm/', 'v.', '开始变得；变成', 'He wants to become a doctor.', '他想成为一名医生。'],
      ['Unit 5', 'rich', '/rɪtʃ/', 'adj.', '富有的', 'The rich man helps poor children.', '这位富人帮助贫困儿童。'],
      ['Unit 5', 'successful', '/səkˈsesfl/', 'adj.', '获得成功的；有成就的', 'The show was very successful.', '演出非常成功。'],
      ['Unit 5', 'might', '/maɪt/', 'modal v.', '可能；可以', 'She might come tomorrow.', '她明天可能会来。'],
      ['Unit 5', 'main', '/meɪn/', 'adj.', '主要的；最重要的', 'The main idea of the text is clear.', '课文的主旨很清楚。'],
      ['Unit 5', 'reason', '/ˈriːzn/', 'n.', '原因；理由', 'Tell me the reason for being late.', '告诉我迟到的原因。'],
      ['Unit 5', 'film', '/fɪlm/', 'n.', '电影', 'We saw a film last night.', '我们昨晚看了一部电影。'],
      ['Unit 5', 'unlucky', '/ʌnˈlʌki/', 'adj.', '不幸的；不吉利的', 'He was unlucky to lose his wallet.', '他不幸丢了钱包。'],
      ['Unit 5', 'lose', '/luːz/', 'v.', '失去；丢失', 'Do not lose your way in the forest.', '别在森林里迷路。'],
      ['Unit 5', 'ready', '/ˈredi/', 'adj.', '愿意的；准备好的', 'Are you ready for the test?', '你准备好考试了吗？'],
      ['Unit 5', 'be ready to', '', 'phr.', '准备好（做某事）；愿意（做某事）', 'She is always ready to help others.', '她总是乐于助人。'],
      ['Unit 5', 'character', '/ˈkærəktə(r)/', 'n.', '人物；角色', 'Mickey Mouse is a famous cartoon character.', '米老鼠是著名的卡通人物。'],
      // Unit 6 I'm going to study computer science.
      ['Unit 6', 'grow up', '', 'phr.', '长大；成熟；成长', 'What do you want to be when you grow up?', '你长大后想做什么？'],
      ['Unit 6', 'computer programmer', '', 'phr.', '计算机程序设计员；编程人员', 'He is a computer programmer.', '他是一名计算机程序员。'],
      ['Unit 6', 'cook', '/kʊk/', 'n.', '厨师', 'My uncle is a great cook.', '我叔叔是个很棒的厨师。'],
      ['Unit 6', 'doctor', '/ˈdɒktə(r)/', 'n.', '医生', 'The doctor told me to rest.', '医生让我休息。'],
      ['Unit 6', 'engineer', '/ˌendʒɪˈnɪə(r)/', 'n.', '工程师', 'Her father is an engineer.', '她的爸爸是工程师。'],
      ['Unit 6', 'violinist', '/ˌvaɪəˈlɪnɪst/', 'n.', '小提琴手', 'The violinist plays beautifully.', '这位小提琴手拉得很优美。'],
      ['Unit 6', 'driver', '/ˈdraɪvə(r)/', 'n.', '驾驶员；司机', 'The bus driver is very kind.', '公交车司机很和蔼。'],
      ['Unit 6', 'pilot', '/ˈpaɪlət/', 'n.', '飞行员', 'A pilot flies a plane.', '飞行员驾驶飞机。'],
      ['Unit 6', 'pianist', '/ˈpɪənɪst/', 'n.', '钢琴家', 'She wants to be a pianist.', '她想成为一名钢琴家。'],
      ['Unit 6', 'scientist', '/ˈsaɪəntɪst/', 'n.', '科学家', 'The scientist studies the stars.', '这位科学家研究星星。'],
      ['Unit 6', 'college', '/ˈkɒlɪdʒ/', 'n.', '学院；大学；高等专科学校', 'He will go to college next year.', '他明年要上大学。'],
      ['Unit 6', 'education', '/ˌedʒuˈkeɪʃn/', 'n.', '教育', 'Education is important to everyone.', '教育对每个人都很重要。'],
      ['Unit 6', 'medicine', '/ˈmedsn/', 'n.', '药；医学', 'Take the medicine twice a day.', '这药一天吃两次。'],
      ['Unit 6', 'university', '/ˌjuːnɪˈvɜːsəti/', 'n.', '（综合性）大学；高等学府', 'She studies English at a university.', '她在大学学英语。'],
      ['Unit 6', 'article', '/ˈɑːtɪkl/', 'n.', '文章；论文', 'He wrote an article for the magazine.', '他为杂志写了一篇文章。'],
      ['Unit 6', 'send', '/send/', 'v.', '邮寄；发送', 'I will send you a postcard.', '我会给你寄明信片。'],
      ['Unit 6', 'resolution', '/ˌrezəˈluːʃn/', 'n.', '决心；决定', 'My New Year resolution is to read more.', '我的新年决心是多读书。'],
      ['Unit 6', 'foreign', '/ˈfɒrən/', 'adj.', '外国的', 'I want to learn a foreign language.', '我想学一门外语。'],
      ['Unit 6', 'able', '/ˈeɪbl/', 'adj.', '能够', 'Are you able to swim?', '你会游泳吗？'],
      ['Unit 6', 'be able to', '', 'phr.', '能够做某事', 'She is able to speak three languages.', '她会说三种语言。'],
      ['Unit 6', 'promise', '/ˈprɒmɪs/', 'n.&v.', '承诺；诺言；许诺', 'He made a promise to his mother.', '他向妈妈许下了承诺。'],
      ['Unit 6', 'beginning', '/bɪˈɡɪnɪŋ/', 'n.', '开头；开端', 'A good beginning is half done.', '良好的开端是成功的一半。'],
      ['Unit 6', 'at the beginning of', '', 'phr.', '在……开始', 'Make a plan at the beginning of the term.', '学期开始时制定计划。'],
      ['Unit 6', 'improve', '/ɪmˈpruːv/', 'v.', '改进；改善', 'I want to improve my English.', '我想提高我的英语水平。'],
      ['Unit 6', 'physical', '/ˈfɪzɪkl/', 'adj.', '身体的', 'Physical exercise keeps us healthy.', '体育锻炼使我们保持健康。'],
      ['Unit 6', 'hobby', '/ˈhɒbi/', 'n.', '业余爱好', 'My hobby is collecting stamps.', '我的爱好是集邮。'],
      ['Unit 6', 'weekly', '/ˈwiːkli/', 'adj.&adv.', '每周的（地）', 'We have a weekly class meeting.', '我们每周开一次班会。'],
      ['Unit 6', 'schoolwork', '/ˈskuːlwɜːk/', 'n.', '学校作业；功课', 'She is busy with her schoolwork.', '她忙于功课。'],
      ['Unit 6', 'agree', '/əˈɡriː/', 'v.', '同意；赞成；应允', 'I agree with your idea.', '我同意你的想法。'],
      ['Unit 6', 'own', '/əʊn/', 'adj.&pron.', '自己的；本人的', 'I saw it with my own eyes.', '我亲眼看到的。'],
      ['Unit 6', 'personal', '/ˈpɜːsənl/', 'adj.', '个人的；私人的', 'This is my personal computer.', '这是我的个人电脑。'],
      ['Unit 6', 'relationship', '/rɪˈleɪʃnʃɪp/', 'n.', '关系；联系', 'They have a good relationship.', '他们关系很好。'],
      // Unit 7 Will people have robots?
      ['Unit 7', 'paper', '/ˈpeɪpə(r)/', 'n.', '纸；纸张', 'Please write on the paper.', '请写在纸上。'],
      ['Unit 7', 'pollution', '/pəˈluːʃn/', 'n.', '污染；污染物', 'Air pollution is a big problem.', '空气污染是个大问题。'],
      ['Unit 7', 'prediction', '/prɪˈdɪkʃn/', 'n.', '预言；预测', 'His prediction came true.', '他的预测成真了。'],
      ['Unit 7', 'future', '/ˈfjuːtʃə(r)/', 'n.', '将来；未来', 'What do you want to be in the future?', '你将来想做什么？'],
      ['Unit 7', 'pollute', '/pəˈluːt/', 'v.', '污染', 'Factories pollute the river.', '工厂污染了河流。'],
      ['Unit 7', 'environment', '/ɪnˈvaɪrənmənt/', 'n.', '环境', 'We should protect the environment.', '我们应该保护环境。'],
      ['Unit 7', 'planet', '/ˈplænɪt/', 'n.', '行星', 'The earth is a planet.', '地球是一颗行星。'],
      ['Unit 7', 'earth', '/ɜːθ/', 'n.', '地球；世界', 'We live on the earth.', '我们生活在地球上。'],
      ['Unit 7', 'plant', '/plɑːnt/', 'v.', '种植', 'We plant trees in spring.', '我们在春天种树。'],
      ['Unit 7', 'part', '/pɑːt/', 'n.', '部分', 'I read part of the book.', '我读了这本书的一部分。'],
      ['Unit 7', 'peace', '/piːs/', 'n.', '和平', 'People all over the world love peace.', '全世界人民都热爱和平。'],
      ['Unit 7', 'sky', '/skaɪ/', 'n.', '天；天空', 'There are many stars in the sky.', '天空中有许多星星。'],
      ['Unit 7', 'fall', '/fɔːl/', 'v.', '倒塌；跌倒；掉落', 'Leaves fall in autumn.', '秋天树叶落下。'],
      ['Unit 7', 'fall in love with', '', 'phr.', '爱上；喜欢上', 'I fell in love with the city.', '我爱上了这座城市。'],
      ['Unit 7', 'alone', '/əˈləʊn/', 'adv.', '单独地；孤独地', 'She lives alone in the house.', '她一个人住在那所房子里。'],
      ['Unit 7', 'pet', '/pet/', 'n.', '宠物', 'I keep a dog as a pet.', '我养了一只狗当宠物。'],
      ['Unit 7', 'probably', '/ˈprɒbəbli/', 'adv.', '很可能；大概', 'It will probably rain tomorrow.', '明天很可能会下雨。'],
      ['Unit 7', 'even', '/ˈiːvn/', 'adv.', '甚至；连；愈加', 'Even a child can answer it.', '连小孩都能回答。'],
      ['Unit 7', 'human', '/ˈhjuːmən/', 'n.', '人；人类', 'Robots can help humans a lot.', '机器人能帮人类很多忙。'],
      ['Unit 7', 'shape', '/ʃeɪp/', 'n.', '形状；外形', 'The cloud has a strange shape.', '那朵云形状很奇怪。'],
      ['Unit 7', 'fewer', '/ˈfjuːə(r)/', 'adj.&pron.', '较少的；更少的', 'There will be fewer trees.', '树木将会更少。'],
      ['Unit 7', 'simple', '/ˈsɪmpl/', 'adj.', '简单的；易做的', 'The question is very simple.', '这个问题很简单。'],
      ['Unit 7', 'believe', '/bɪˈliːv/', 'v.', '相信；认为有可能', 'I believe what you say.', '我相信你说的话。'],
      ['Unit 7', 'disagree', '/ˌdɪsəˈɡriː/', 'v.', '不同意；持不同意见；有分歧', 'I disagree with you on this point.', '在这一点上我不同意你。'],
      ['Unit 7', 'hundreds of', '', 'phr.', '许多；大量', 'Hundreds of people came to the park.', '成百上千的人来到公园。'],
      ['Unit 7', 'space', '/speɪs/', 'n.', '太空；空间', 'Rockets can fly into space.', '火箭能飞入太空。'],
      ['Unit 7', 'fly', '/flaɪ/', 'v.', '飞', 'Birds can fly in the sky.', '鸟能在天空中飞。'],
      ['Unit 7', 'rocket', '/ˈrɒkɪt/', 'n.', '火箭', 'The rocket flew up into space.', '火箭飞上了太空。'],
      ['Unit 7', 'astronaut', '/ˈæstrənɔːt/', 'n.', '宇航员；航天员', 'The astronaut walked on the moon.', '宇航员在月球上行走。'],
      ['Unit 7', 'moon', '/muːn/', 'n.', '月球；月亮', 'The moon is bright tonight.', '今晚月亮很亮。'],
      // Unit 8 How do you make a banana milk shake?
      ['Unit 8', 'shake', '/ʃeɪk/', 'n.&v.', '奶昔；摇动；抖动', 'Give the bottle a good shake.', '把瓶子好好摇一摇。'],
      ['Unit 8', 'milk shake', '', 'phr.', '奶昔', 'I like banana milk shake.', '我喜欢香蕉奶昔。'],
      ['Unit 8', 'blender', '/ˈblendə(r)/', 'n.', '食物搅拌器', 'Put the fruit in the blender.', '把水果放进搅拌器。'],
      ['Unit 8', 'peel', '/piːl/', 'v.', '剥皮；去皮', 'Please peel the apple for me.', '请帮我削苹果皮。'],
      ['Unit 8', 'pour', '/pɔː(r)/', 'v.', '倒出；倾倒', 'Pour the milk into the cup.', '把牛奶倒进杯子里。'],
      ['Unit 8', 'yogurt', '/ˈjɒɡət/', 'n.', '酸奶', 'I have yogurt for breakfast.', '我早餐喝酸奶。'],
      ['Unit 8', 'honey', '/ˈhʌni/', 'n.', '蜂蜜', 'Honey is sweet.', '蜂蜜是甜的。'],
      ['Unit 8', 'watermelon', '/ˈwɔːtəmelən/', 'n.', '西瓜', 'The watermelon is very sweet.', '西瓜很甜。'],
      ['Unit 8', 'spoon', '/spuːn/', 'n.', '勺；调羹', 'Eat soup with a spoon.', '用勺子喝汤。'],
      ['Unit 8', 'pot', '/pɒt/', 'n.', '锅', 'The soup is in the pot.', '汤在锅里。'],
      ['Unit 8', 'add', '/æd/', 'v.', '增加；添加', 'Add some sugar to the tea.', '往茶里加点糖。'],
      ['Unit 8', 'finally', '/ˈfaɪnəli/', 'adv.', '最后；最终', 'Finally, we finished the work.', '最后，我们完成了工作。'],
      ['Unit 8', 'mix', '/mɪks/', 'v.', '（使）混合；融合', 'Mix the eggs and milk together.', '把鸡蛋和牛奶混合在一起。'],
      ['Unit 8', 'popcorn', '/ˈpɒpkɔːn/', 'n.', '爆米花', 'We eat popcorn at the cinema.', '我们在电影院吃爆米花。'],
      ['Unit 8', 'machine', '/məˈʃiːn/', 'n.', '机器；机械装置', 'This machine makes popcorn.', '这台机器做爆米花。'],
      ['Unit 8', 'salt', '/sɔːlt/', 'n.', '盐', 'Add a little salt to the soup.', '往汤里加一点盐。'],
      ['Unit 8', 'sandwich', '/ˈsænwɪtʃ/', 'n.', '夹心面包片；三明治', 'I had a sandwich for lunch.', '我午饭吃了一个三明治。'],
      ['Unit 8', 'butter', '/ˈbʌtə(r)/', 'n.', '黄油；奶油', 'Spread butter on the bread.', '把黄油涂在面包上。'],
      ['Unit 8', 'recipe', '/ˈresəpi/', 'n.', '烹饪法；食谱', 'This is a recipe for chicken soup.', '这是一份鸡汤的做法。'],
      ['Unit 8', 'ingredient', '/ɪnˈɡriːdiənt/', 'n.', '（烹调用的）材料；原料；成分', 'Flour is the main ingredient of bread.', '面粉是面包的主要原料。'],
      ['Unit 8', 'instruction', '/ɪnˈstrʌkʃn/', 'n.', '指示；命令；用法说明', 'Read the instructions before you start.', '开始前请阅读说明。'],
      ['Unit 8', 'turn on', '', 'phr.', '接通（电流、煤气、水等）；打开', 'Please turn on the light.', '请把灯打开。'],
      ['Unit 8', 'cut up', '', 'phr.', '切碎', 'Cut up the carrots first.', '先把胡萝卜切碎。'],
      // Unit 9 Can you come to my party?
      ['Unit 9', 'prepare', '/prɪˈpeə(r)/', 'v.', '使做好准备；把……准备好', 'We are preparing for the exam.', '我们正在为考试做准备。'],
      ['Unit 9', 'prepare for', '', 'phr.', '为……做准备', 'She is preparing for the party.', '她正在为聚会做准备。'],
      ['Unit 9', 'exam', '/ɪɡˈzæm/', 'n.', '考试', 'We have an English exam on Friday.', '我们星期五有英语考试。'],
      ['Unit 9', 'flu', '/fluː/', 'n.', '流行性感冒；流感', 'He stayed at home with the flu.', '他得了流感待在家里。'],
      ['Unit 9', 'available', '/əˈveɪləbl/', 'adj.', '有空的；可获得的', 'Are you available this weekend?', '你这周末有空吗？'],
      ['Unit 9', 'another', '/əˈnʌðə(r)/', 'adj.&pron.', '另一；又一', 'Would you like another cup of tea?', '你要再来一杯茶吗？'],
      ['Unit 9', 'invite', '/ɪnˈvaɪt/', 'v.', '邀请', 'I want to invite you to my party.', '我想邀请你参加我的聚会。'],
      ['Unit 9', 'accept', '/əkˈsept/', 'v.', '接受', 'She accepted my invitation.', '她接受了我的邀请。'],
      ['Unit 9', 'refuse', '/rɪˈfjuːz/', 'v.', '拒绝', 'He refused to answer the question.', '他拒绝回答这个问题。'],
      ['Unit 9', 'reply', '/rɪˈplaɪ/', 'v.&n.', '回答；答复', 'Please reply to my e-mail soon.', '请尽快回复我的邮件。'],
      ['Unit 9', 'forward', '/ˈfɔːwəd/', 'v.&adv.', '转寄；发送；向前', 'Please forward the message to him.', '请把消息转发给他。'],
      ['Unit 9', 'delete', '/dɪˈliːt/', 'v.', '删除', 'Please delete the wrong word.', '请把错词删掉。'],
      ['Unit 9', 'print', '/prɪnt/', 'v.', '打印', 'Print the document for me, please.', '请帮我打印这份文件。'],
      ['Unit 9', 'sad', '/sæd/', 'adj.', '（令人）悲哀的；（令人）难过的', 'She felt sad when she left home.', '离开家时她很难过。'],
      ['Unit 9', 'goodbye', '/ˌɡʊdˈbaɪ/', 'interj.&n.', '再见', 'We said goodbye at the gate.', '我们在大门口道别。'],
      ['Unit 9', 'glad', '/ɡlæd/', 'adj.', '高兴的；愿意的', 'I am glad to see you.', '见到你我很高兴。'],
      ['Unit 9', 'preparation', '/ˌprepəˈreɪʃn/', 'n.', '准备；准备工作', 'We made preparations for the trip.', '我们为旅行做了准备。'],
      ['Unit 9', 'hang out', '', 'phr.', '闲逛；常去某处', 'We often hang out in the mall.', '我们经常在商场闲逛。'],
      ['Unit 9', 'the day before yesterday', '', 'phr.', '前天', 'I met him the day before yesterday.', '我前天遇到了他。'],
      ['Unit 9', 'the day after tomorrow', '', 'phr.', '后天', 'We will have a test the day after tomorrow.', '我们后天有测验。'],
      ['Unit 9', 'look after', '', 'phr.', '照料；照顾', 'Please look after my dog.', '请照顾我的狗。'],
      ['Unit 9', 'turn down', '', 'phr.', '拒绝', 'She turned down the invitation.', '她拒绝了邀请。'],
      ['Unit 9', 'take a trip', '', 'phr.', '去旅行', 'We will take a trip to Beijing.', '我们要去北京旅行。'],
      ['Unit 9', 'hear from', '', 'phr.', '接到（某人的）信、电话等', 'I hope to hear from you soon.', '我希望很快收到你的来信。'],
      // Unit 10 If you go to the party, you'll have a great time!
      ['Unit 10', 'meeting', '/ˈmiːtɪŋ/', 'n.', '会议；集会；会面', 'We have a class meeting on Monday.', '我们星期一开班会。'],
      ['Unit 10', 'organize', '/ˈɔːɡənaɪz/', 'v.', '组织；筹备', 'They will organize a football game.', '他们将组织一场足球赛。'],
      ['Unit 10', 'chocolate', '/ˈtʃɒklət/', 'n.', '巧克力', 'Children love chocolate.', '孩子们喜欢巧克力。'],
      ['Unit 10', 'upset', '/ʌpˈset/', 'adj.', '难过；失望；沮丧', 'She was upset about the bad news.', '她为这个坏消息难过。'],
      ['Unit 10', 'taxi', '/ˈtæksi/', 'n.', '出租车；的士', 'Let us take a taxi home.', '我们坐出租车回家吧。'],
      ['Unit 10', 'advice', '/ədˈvaɪs/', 'n.', '劝告；建议', 'Can you give me some advice?', '你能给我一些建议吗？'],
      ['Unit 10', 'travel', '/ˈtrævl/', 'v.&n.', '旅行；游历', 'I want to travel around China.', '我想环游中国。'],
      ['Unit 10', 'agent', '/ˈeɪdʒənt/', 'n.', '代理人；经纪人', 'The travel agent helped us a lot.', '旅行社的人帮了我们很多。'],
      ['Unit 10', 'expert', '/ˈekspɜːt/', 'n.', '专家', 'He is an expert on computers.', '他是计算机专家。'],
      ['Unit 10', 'teenager', '/ˈtiːneɪdʒə(r)/', 'n.', '（13-19岁的）青少年', 'The book is popular with teenagers.', '这本书很受青少年欢迎。'],
      ['Unit 10', 'certainly', '/ˈsɜːtnli/', 'adv.', '无疑；肯定；当然；行', 'I will certainly help you.', '我当然会帮你。'],
      ['Unit 10', 'wallet', '/ˈwɒlɪt/', 'n.', '钱包', 'I lost my wallet on the bus.', '我在公交车上丢了钱包。'],
      ['Unit 10', 'mile', '/maɪl/', 'n.', '英里', 'The school is two miles away.', '学校在两英里外。'],
      ['Unit 10', 'angry', '/ˈæŋɡri/', 'adj.', '发怒的；生气的', 'Do not be angry with me.', '别生我的气。'],
      ['Unit 10', 'understanding', '/ˌʌndəˈstændɪŋ/', 'adj.', '善解人意的；体谅人的', 'She is an understanding friend.', '她是一位善解人意的朋友。'],
      ['Unit 10', 'careless', '/ˈkeələs/', 'adj.', '粗心的；不小心的', 'He made a careless mistake.', '他犯了一个粗心的错误。'],
      ['Unit 10', 'mistake', '/mɪˈsteɪk/', 'n.', '错误；失误', 'Everyone makes mistakes.', '每个人都会犯错。'],
      ['Unit 10', 'himself', '/hɪmˈself/', 'pron.', '他自己', 'He did the work by himself.', '他独自完成了工作。'],
      ['Unit 10', 'careful', '/ˈkeəfl/', 'adj.', '小心的；细致的；精心的；慎重的', 'Be careful when you cross the road.', '过马路时要小心。'],
      ['Unit 10', 'advise', '/ədˈvaɪz/', 'v.', '劝告；建议', 'The doctor advised him to rest.', '医生建议他休息。'],
      ['Unit 10', 'solve', '/sɒlv/', 'v.', '解决；解答', 'Can you solve this problem?', '你能解决这个问题吗？'],
      ['Unit 10', 'step', '/step/', 'n.', '步；步骤', 'Follow these steps to make tea.', '按照这些步骤来泡茶。'],
      ['Unit 10', 'trust', '/trʌst/', 'v.&n.', '相信；信任', 'I trust my best friend.', '我信任我最好的朋友。'],
      ['Unit 10', 'experience', '/ɪkˈspɪəriəns/', 'n.', '经验；经历', 'He has much teaching experience.', '他有丰富的教学经验。'],
      ['Unit 10', 'else', '/els/', 'adv.', '另外；其他', 'What else do you want?', '你还想要什么？'],
      ['Unit 10', 'in half', '', 'phr.', '分成两半', 'Cut the apple in half.', '把苹果切成两半。'],
    ],
  };
  if (typeof window !== 'undefined') {
    window.VocabSampleBooks = window.VocabSampleBooks || [];
    window.VocabSampleBooks.push(book);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = book;
})();
