/**
 * 示例词库：人教版八年级下册（Unit 1-10）
 * 每行：[单元, 单词, 音标, 词性, 中文释义, 例句, 例句翻译]
 */
(function () {
  const book = {
    key: 'g8b',
    name: '示例词库-人教版八年级下册',
    file: '示例词库-人教版八年级下册.xlsx',
    words: [
      // Unit 1 What's the matter?
      ['Unit 1', 'matter', '/ˈmætə(r)/', 'n.', '问题；事情', 'What is the matter with you?', '你怎么了？'],
      ['Unit 1', 'sore', '/sɔː(r)/', 'adj.', '疼痛的；酸痛的', 'I have a sore throat.', '我嗓子疼。'],
      ['Unit 1', 'stomachache', '/ˈstʌməkeɪk/', 'n.', '胃痛；腹痛', 'He has a stomachache today.', '他今天胃痛。'],
      ['Unit 1', 'foot', '/fʊt/', 'n.', '脚；足', 'My feet hurt after walking.', '走路后我的脚疼。'],
      ['Unit 1', 'neck', '/nek/', 'n.', '颈；脖子', 'The giraffe has a long neck.', '长颈鹿有长长的脖子。'],
      ['Unit 1', 'stomach', '/ˈstʌmək/', 'n.', '胃；腹部', 'Do not read on an empty stomach.', '不要空腹看书。'],
      ['Unit 1', 'throat', '/θrəʊt/', 'n.', '咽喉；喉咙', 'Drink water when your throat is dry.', '喉咙干的时候喝点水。'],
      ['Unit 1', 'fever', '/ˈfiːvə(r)/', 'n.', '发烧', 'The boy has a high fever.', '这个男孩发高烧。'],
      ['Unit 1', 'lie', '/laɪ/', 'v.', '躺；平躺', 'Lie down and have a rest.', '躺下休息一会儿。'],
      ['Unit 1', 'rest', '/rest/', 'v.&n.', '放松；休息', 'You should rest after work.', '工作后你应该休息。'],
      ['Unit 1', 'cough', '/kɒf/', 'n.&v.', '咳嗽', 'She has a bad cough.', '她咳嗽得厉害。'],
      ['Unit 1', 'toothache', '/ˈtuːθeɪk/', 'n.', '牙痛', 'I have a toothache and need a dentist.', '我牙痛，需要看牙医。'],
      ['Unit 1', 'headache', '/ˈhedeɪk/', 'n.', '头痛', 'I have a headache after reading.', '看书后我头痛。'],
      ['Unit 1', 'hurt', '/hɜːt/', 'v.', '（使）疼痛；受伤', 'My leg hurts.', '我的腿疼。'],
      ['Unit 1', 'passenger', '/ˈpæsɪndʒə(r)/', 'n.', '乘客；旅客', 'All passengers got on the bus.', '所有乘客都上了公交车。'],
      ['Unit 1', 'off', '/ɒf/', 'adv.&prep.', '离开（某处）；不工作；从……去掉', 'Please get off at the next stop.', '请在下一站下车。'],
      ['Unit 1', 'onto', '/ˈɒntə/', 'prep.', '向；朝', 'The cat jumped onto the table.', '猫跳到了桌子上。'],
      ['Unit 1', 'trouble', '/ˈtrʌbl/', 'n.', '问题；苦恼', 'He is in trouble now.', '他现在有麻烦了。'],
      ['Unit 1', 'hit', '/hɪt/', 'v.', '（用手或器具）击；打', 'The ball hit the window.', '球打中了窗户。'],
      ['Unit 1', 'herself', '/hɜːˈself/', 'pron.', '她自己', 'She made the cake herself.', '她自己做的蛋糕。'],
      ['Unit 1', 'bandage', '/ˈbændɪdʒ/', 'n.&v.', '绷带；用绷带包扎', 'Put a bandage on the cut.', '在伤口上缠上绷带。'],
      ['Unit 1', 'sick', '/sɪk/', 'adj.', '生病的；有病的', 'The sick boy needs a doctor.', '这个生病的男孩需要医生。'],
      ['Unit 1', 'knee', '/niː/', 'n.', '膝；膝盖', 'He fell and hurt his knee.', '他摔倒了，伤了膝盖。'],
      ['Unit 1', 'climber', '/ˈklaɪmə(r)/', 'n.', '登山者；攀登者', 'The climbers reached the top.', '登山者们到达了山顶。'],
      ['Unit 1', 'risk', '/rɪsk/', 'n.&v.', '危险；风险；冒险', 'Do not take risks in the mountains.', '不要在山里冒险。'],
      ['Unit 1', 'accident', '/ˈæksɪdənt/', 'n.', '（交通）事故；意外遭遇', 'There was a car accident on the road.', '路上发生了一起车祸。'],
      ['Unit 1', 'situation', '/ˌsɪtʃuˈeɪʃn/', 'n.', '情况；状况', 'The situation is getting better.', '情况正在好转。'],
      ['Unit 1', 'kilo', '/ˈkiːləʊ/', 'n.', '千克；公斤', 'I bought two kilos of apples.', '我买了两公斤苹果。'],
      ['Unit 1', 'rock', '/rɒk/', 'n.', '岩石', 'The boy climbed up the rock.', '男孩爬上了岩石。'],
      ['Unit 1', 'knife', '/naɪf/', 'n.', '刀', 'Be careful with the knife.', '小心刀子。'],
      ['Unit 1', 'blood', '/blʌd/', 'n.', '血', 'There is blood on his hand.', '他手上有血。'],
      ['Unit 1', 'mean', '/miːn/', 'v.', '意思是；打算；意欲', 'What does this word mean?', '这个词是什么意思？'],
      ['Unit 1', 'importance', '/ɪmˈpɔːtns/', 'n.', '重要性', 'We know the importance of health.', '我们知道健康的重要性。'],
      ['Unit 1', 'decision', '/dɪˈsɪʒn/', 'n.', '决定；抉择', 'It is a big decision for her.', '这对她来说是个重大决定。'],
      ['Unit 1', 'control', '/kənˈtrəʊl/', 'n.&v.', '限制；约束；管理', 'The driver lost control of the car.', '司机失去了对车的控制。'],
      ['Unit 1', 'spirit', '/ˈspɪrɪt/', 'n.', '勇气；意志；精神', 'Team spirit is important.', '团队精神很重要。'],
      ['Unit 1', 'death', '/deθ/', 'n.', '死；死亡', 'The death of the dog made her sad.', '狗的死让她很伤心。'],
      ['Unit 1', 'nurse', '/nɜːs/', 'n.', '护士', 'The nurse takes care of the sick.', '护士照顾病人。'],
      ['Unit 1', 'give up', '', 'phr.', '放弃', 'Never give up your dream.', '永远不要放弃你的梦想。'],
      // Unit 2 I'll help to clean up the city parks.
      ['Unit 2', 'cheer', '/tʃɪə(r)/', 'v.', '欢呼；喝彩', 'The fans cheered for their team.', '球迷们为他们的队欢呼。'],
      ['Unit 2', 'cheer up', '', 'phr.', '（使）变得更高兴；振奋起来', 'Let us cheer her up.', '我们让她高兴起来吧。'],
      ['Unit 2', 'volunteer', '/ˌvɒlənˈtɪə(r)/', 'v.&n.', '义务做；自愿做；志愿者', 'She volunteers at the hospital.', '她在医院做志愿者。'],
      ['Unit 2', 'sign', '/saɪn/', 'n.', '标志；信号', 'Look at the sign over there.', '看那边的标志。'],
      ['Unit 2', 'notice', '/ˈnəʊtɪs/', 'n.&v.', '通知；通告；注意到', 'I noticed a bird in the tree.', '我注意到树上有一只鸟。'],
      ['Unit 2', 'lonely', '/ˈləʊnli/', 'adj.', '孤独的；寂寞的', 'The old man feels lonely.', '那位老人感到孤独。'],
      ['Unit 2', 'several', '/ˈsevrəl/', 'pron.', '几个；数个；一些', 'I have read the book several times.', '这本书我读过好几遍了。'],
      ['Unit 2', 'raise', '/reɪz/', 'v.', '募集；征集；举起', 'We raised money for the poor.', '我们为穷人筹款。'],
      ['Unit 2', 'alone', '/əˈləʊn/', 'adj.', '独自的；单独的', 'She was alone in the room.', '她独自一人在房间里。'],
      ['Unit 2', 'repair', '/rɪˈpeə(r)/', 'v.&n.', '修理；修补', 'He is repairing his bike.', '他在修自行车。'],
      ['Unit 2', 'fix', '/fɪks/', 'v.', '修理；安装', 'Can you fix the broken chair?', '你能修好这把坏椅子吗？'],
      ['Unit 2', 'wheel', '/wiːl/', 'n.', '轮；车轮', 'A car has four wheels.', '汽车有四个轮子。'],
      ['Unit 2', 'letter', '/ˈletə(r)/', 'n.', '信；函', 'I wrote a letter to my friend.', '我给朋友写了一封信。'],
      ['Unit 2', 'disabled', '/dɪsˈeɪbld/', 'adj.', '丧失能力的；有残疾的', 'We should help disabled people.', '我们应该帮助残疾人。'],
      ['Unit 2', 'blind', '/blaɪnd/', 'adj.', '瞎的；失明的', 'The blind man has a guide dog.', '这位盲人有一只导盲犬。'],
      ['Unit 2', 'deaf', '/def/', 'adj.', '聋的', 'The deaf girl uses sign language.', '这个失聪的女孩用手语。'],
      ['Unit 2', 'imagine', '/ɪˈmædʒɪn/', 'v.', '想象；设想', 'Imagine you are on the moon.', '想象你在月球上。'],
      ['Unit 2', 'difficulty', '/ˈdɪfɪkəlti/', 'n.', '困难；难题', 'He has difficulty walking.', '他走路有困难。'],
      ['Unit 2', 'carry', '/ˈkæri/', 'v.', '拿；提；扛', 'Let me carry the bag for you.', '让我帮你提包吧。'],
      ['Unit 2', 'train', '/treɪn/', 'v.', '训练；培训', 'They train dogs to help the blind.', '他们训练狗帮助盲人。'],
      ['Unit 2', 'excited', '/ɪkˈsaɪtɪd/', 'adj.', '激动的；兴奋的', 'The children were excited about the trip.', '孩子们对旅行感到兴奋。'],
      ['Unit 2', 'training', '/ˈtreɪnɪŋ/', 'n.', '训练；培训', 'The training starts at nine.', '训练九点开始。'],
      ['Unit 2', 'kindness', '/ˈkaɪndnəs/', 'n.', '仁慈；善良', 'Thank you for your kindness.', '谢谢你的好意。'],
      ['Unit 2', 'clever', '/ˈklevə(r)/', 'adj.', '聪明的；聪颖的', 'The clever boy answered quickly.', '这个聪明的男孩回答得很快。'],
      ['Unit 2', 'understand', '/ˌʌndəˈstænd/', 'v.', '理解；领会', 'I understand your problem.', '我理解你的问题。'],
      ['Unit 2', 'change', '/tʃeɪndʒ/', 'v.&n.', '变化；改变', 'Volunteering changed my life.', '志愿活动改变了我的生活。'],
      ['Unit 2', 'interest', '/ˈɪntrəst/', 'n.&v.', '兴趣；关注；使感兴趣', 'She shows interest in science.', '她对科学表现出兴趣。'],
      ['Unit 2', 'hand out', '', 'phr.', '分发', 'Please hand out the books.', '请把书发下去。'],
      ['Unit 2', 'call up', '', 'phr.', '打电话给（某人）；征召', 'Call me up when you arrive.', '你到了就给我打电话。'],
      ['Unit 2', 'care for', '', 'phr.', '照顾；非常喜欢', 'She cares for the old people.', '她照顾老人。'],
      ['Unit 2', 'fix up', '', 'phr.', '修理；装饰', 'He fixed up the old bike.', '他修好了那辆旧自行车。'],
      ['Unit 2', 'give away', '', 'phr.', '赠送；捐赠', 'He gave away his old toys.', '他把旧玩具送人了。'],
      ['Unit 2', 'set up', '', 'phr.', '建起；设立', 'They set up a new school.', '他们建起了一所新学校。'],
      // Unit 3 Could you please clean your room?
      ['Unit 3', 'rubbish', '/ˈrʌbɪʃ/', 'n.', '垃圾；废弃物', 'Please take out the rubbish.', '请把垃圾倒了。'],
      ['Unit 3', 'fold', '/fəʊld/', 'v.', '折叠；对折', 'Fold your clothes, please.', '请把你的衣服叠好。'],
      ['Unit 3', 'sweep', '/swiːp/', 'v.', '扫；打扫', 'She sweeps the floor every day.', '她每天扫地。'],
      ['Unit 3', 'mess', '/mes/', 'n.', '杂乱；不整洁', 'Your room is in a mess.', '你的房间乱七八糟。'],
      ['Unit 3', 'shirt', '/ʃɜːt/', 'n.', '衬衫', 'He wears a white shirt today.', '他今天穿了一件白衬衫。'],
      ['Unit 3', 'pass', '/pɑːs/', 'v.', '给；递；走过；通过', 'Please pass me the salt.', '请把盐递给我。'],
      ['Unit 3', 'borrow', '/ˈbɒrəʊ/', 'v.', '借；借用', 'May I borrow your pen?', '我可以借你的钢笔吗？'],
      ['Unit 3', 'lend', '/lend/', 'v.', '借给；借出', 'Can you lend me your book?', '你能把书借给我吗？'],
      ['Unit 3', 'neither', '/ˈnaɪðə(r)/', 'pron.', '两者都不', 'Neither answer is correct.', '两个答案都不对。'],
      ['Unit 3', 'while', '/waɪl/', 'conj.', '与……同时；当……的时候', 'I read while I wait.', '我一边等一边看书。'],
      ['Unit 3', 'snack', '/snæk/', 'n.', '点心；小吃；快餐', 'We bought some snacks for the trip.', '我们为旅行买了些零食。'],
      ['Unit 3', 'stress', '/stres/', 'n.', '精神压力；心理负担', 'Students are under much stress.', '学生们压力很大。'],
      ['Unit 3', 'waste', '/weɪst/', 'n.&v.', '浪费；垃圾；浪费', 'Do not waste your time.', '不要浪费你的时间。'],
      ['Unit 3', 'provide', '/prəˈvaɪd/', 'v.', '提供；供应', 'The school provides free lunch.', '学校提供免费午餐。'],
      ['Unit 3', 'anyway', '/ˈeniweɪ/', 'adv.', '而且；加之', 'It is too late; anyway, I am tired.', '太晚了，而且我也累了。'],
      ['Unit 3', 'depend', '/dɪˈpend/', 'v.', '依靠；信赖', 'Children depend on their parents.', '孩子依靠父母。'],
      ['Unit 3', 'depend on', '', 'phr.', '依靠；信赖', 'You can depend on me.', '你可以信赖我。'],
      ['Unit 3', 'develop', '/dɪˈveləp/', 'v.', '发展；壮大；培养', 'Reading develops the mind.', '阅读能开发智力。'],
      ['Unit 3', 'fairness', '/ˈfeənəs/', 'n.', '公正性；合理性', 'Everyone wants fairness.', '每个人都想要公平。'],
      ['Unit 3', 'since', '/sɪns/', 'conj.', '因为；既然；从……以后', 'Since you are here, let us start.', '既然你来了，我们开始吧。'],
      ['Unit 3', 'neighbor', '/ˈneɪbə(r)/', 'n.', '邻居', 'Our neighbors are very friendly.', '我们的邻居很友好。'],
      ['Unit 3', 'ill', '/ɪl/', 'adj.', '有病；不舒服', 'She is ill in bed.', '她卧病在床。'],
      ['Unit 3', 'drop', '/drɒp/', 'v.', '落下；掉下', 'Be careful not to drop the cup.', '小心别把杯子掉了。'],
      ['Unit 3', 'independent', '/ˌɪndɪˈpendənt/', 'adj.', '独立的；自主的', 'She is independent at school.', '她在学校很独立。'],
      ['Unit 3', 'independence', '/ˌɪndɪˈpendəns/', 'n.', '独立', 'Children should learn independence.', '孩子们应该学会独立。'],
      ['Unit 3', 'fair', '/feə(r)/', 'adj.', '合理的；公正的', 'It is fair to share the work.', '分担工作是公平的。'],
      ['Unit 3', 'unfair', '/ˌʌnˈfeə(r)/', 'adj.', '不合理的；不公正的', 'It is unfair to laugh at others.', '嘲笑别人是不公平的。'],
      ['Unit 3', 'take care of', '', 'phr.', '照顾；处理', 'Take care of your little sister.', '照顾好你的妹妹。'],
      // Unit 4 Why don't you talk to your parents?
      ['Unit 4', 'allow', '/əˈlaʊ/', 'v.', '允许；准许', 'My parents allow me to play on weekends.', '我父母允许我周末玩。'],
      ['Unit 4', 'wrong', '/rɒŋ/', 'adj.', '有毛病；错误的', 'What is wrong with your bike?', '你的自行车怎么了？'],
      ['Unit 4', 'midnight', '/ˈmɪdnaɪt/', 'n.', '午夜；子夜', 'He came back at midnight.', '他午夜才回来。'],
      ['Unit 4', 'guess', '/ɡes/', 'v.', '猜测；估计', 'Guess what is in the box.', '猜猜盒子里有什么。'],
      ['Unit 4', 'deal', '/diːl/', 'n.', '协议；交易', 'We made a deal with them.', '我们和他们达成了协议。'],
      ['Unit 4', 'relation', '/rɪˈleɪʃn/', 'n.', '关系；联系；交往', 'Their relation is getting better.', '他们的关系正在好转。'],
      ['Unit 4', 'communication', '/kəˌmjuːnɪˈkeɪʃn/', 'n.', '交流；沟通', 'Communication is important in a family.', '沟通在家庭中很重要。'],
      ['Unit 4', 'argue', '/ˈɑːɡjuː/', 'v.', '争吵；争论', 'They often argue about small things.', '他们经常为小事争吵。'],
      ['Unit 4', 'cloud', '/klaʊd/', 'n.', '云；云朵', 'White clouds are in the sky.', '天空中有白云。'],
      ['Unit 4', 'elder', '/ˈeldə(r)/', 'adj.', '年纪较长的', 'My elder brother is a doctor.', '我哥哥是医生。'],
      ['Unit 4', 'instead', '/ɪnˈsted/', 'adv.', '代替；反而；却', 'He did not cry; instead, he smiled.', '他没有哭，反而笑了。'],
      ['Unit 4', 'whatever', '/wɒtˈevə(r)/', 'pron.', '任何；每一', 'Whatever you do, do it well.', '无论做什么，都要做好。'],
      ['Unit 4', 'nervous', '/ˈnɜːvəs/', 'adj.', '焦虑的；担忧的', 'I feel nervous before exams.', '考试前我感到紧张。'],
      ['Unit 4', 'offer', '/ˈɒfə(r)/', 'v.', '主动提出；自愿给予', 'He offered to help me.', '他主动提出帮助我。'],
      ['Unit 4', 'proper', '/ˈprɒpə(r)/', 'adj.', '正确的；恰当的', 'Use the proper word in the blank.', '在空白处用恰当的词。'],
      ['Unit 4', 'secondly', '/ˈsekəndli/', 'adv.', '第二；其次', 'Firstly, it is cheap; secondly, it is good.', '首先它便宜，其次它很好。'],
      ['Unit 4', 'communicate', '/kəˈmjuːnɪkeɪt/', 'v.', '交流；沟通', 'We should communicate with our parents.', '我们应该和父母沟通。'],
      ['Unit 4', 'explain', '/ɪkˈspleɪn/', 'v.', '解释；说明', 'Can you explain the answer to me?', '你能给我解释一下答案吗？'],
      ['Unit 4', 'clear', '/klɪə(r)/', 'adj.', '清楚易懂的；晴朗的', 'The sky is clear after the rain.', '雨后天空晴朗。'],
      ['Unit 4', 'copy', '/ˈkɒpi/', 'v.', '抄袭；模仿；复制', 'Do not copy others homework.', '不要抄别人的作业。'],
      ['Unit 4', 'return', '/rɪˈtɜːn/', 'v.', '归还；回来；返回', 'Please return the book on time.', '请按时归还图书。'],
      ['Unit 4', 'anymore', '/ˌeniˈmɔː(r)/', 'adv.', '再（不）；（不）再', 'I do not play games anymore.', '我不再玩游戏了。'],
      ['Unit 4', 'pressure', '/ˈpreʃə(r)/', 'n.', '压力', 'Students have much pressure now.', '现在学生压力很大。'],
      ['Unit 4', 'compete', '/kəmˈpiːt/', 'v.', '竞争；对抗', 'The two teams compete for the cup.', '两队争夺奖杯。'],
      ['Unit 4', 'opinion', '/əˈpɪnjən/', 'n.', '意见；想法；看法', 'What is your opinion on this?', '你对此有什么看法？'],
      ['Unit 4', 'skill', '/skɪl/', 'n.', '技艺；技巧', 'Reading is an important skill.', '阅读是一项重要的技能。'],
      ['Unit 4', 'typical', '/ˈtɪpɪkl/', 'adj.', '典型的；有代表性的', 'This is a typical English breakfast.', '这是典型的英式早餐。'],
      ['Unit 4', 'football', '/ˈfʊtbɔːl/', 'n.', '（美式）橄榄球；足球', 'The boys are playing football.', '男孩们在踢足球。'],
      ['Unit 4', 'quick', '/kwɪk/', 'adj.', '快的；迅速的', 'He gave a quick answer.', '他很快给出了答案。'],
      ['Unit 4', 'continue', '/kənˈtɪnjuː/', 'v.', '继续；持续', 'The rain continued all day.', '雨持续下了一整天。'],
      ['Unit 4', 'compare', '/kəmˈpeə(r)/', 'v.', '比较', 'Do not compare yourself with others.', '不要拿自己和别人比较。'],
      ['Unit 4', 'crazy', '/ˈkreɪzi/', 'adj.', '疯狂的；狂热的', 'The kids are crazy about games.', '孩子们对游戏很着迷。'],
      ['Unit 4', 'push', '/pʊʃ/', 'v.', '鞭策；督促；推动', 'Parents should not push kids too hard.', '父母不应该把孩子逼得太紧。'],
      ['Unit 4', 'development', '/dɪˈveləpmənt/', 'n.', '发展；发育；成长', 'Sleep is good for children development.', '睡眠有益于孩子的成长。'],
      ['Unit 4', 'cause', '/kɔːz/', 'v.&n.', '造成；引起；原因', 'The rain caused a flood.', '大雨引发了洪水。'],
      ['Unit 4', 'usual', '/ˈjuːʒuəl/', 'adj.', '通常的；寻常的', 'He got up earlier than usual.', '他比平时起得早。'],
      ['Unit 4', 'perhaps', '/pəˈhæps/', 'adv.', '可能；大概；也许', 'Perhaps it will rain tomorrow.', '明天也许会下雨。'],
      ['Unit 4', 'work out', '', 'phr.', '解决；成功地发展', 'I believe things will work out.', '我相信事情会解决的。'],
      // Unit 5 What were you doing when the rainstorm came?
      ['Unit 5', 'rainstorm', '/ˈreɪnstɔːm/', 'n.', '暴风雨', 'The rainstorm came at night.', '暴风雨在夜里来临。'],
      ['Unit 5', 'alarm', '/əˈlɑːm/', 'n.', '闹钟', 'My alarm rings at six.', '我的闹钟六点响。'],
      ['Unit 5', 'begin', '/bɪˈɡɪn/', 'v.', '开始', 'The film begins at seven.', '电影七点开始。'],
      ['Unit 5', 'heavily', '/ˈhevɪli/', 'adv.', '在很大程度上；大量地', 'It rained heavily yesterday.', '昨天雨下得很大。'],
      ['Unit 5', 'strange', '/streɪndʒ/', 'adj.', '奇特的；奇怪的', 'I heard a strange sound.', '我听到一个奇怪的声音。'],
      ['Unit 5', 'storm', '/stɔːm/', 'n.', '暴风雨', 'The storm lasted two hours.', '暴风雨持续了两个小时。'],
      ['Unit 5', 'wind', '/wɪnd/', 'n.', '风', 'The wind is strong today.', '今天风很大。'],
      ['Unit 5', 'light', '/laɪt/', 'n.', '光；光线；光亮', 'The light in the room is bright.', '房间里的灯很亮。'],
      ['Unit 5', 'report', '/rɪˈpɔːt/', 'n.&v.', '报道；公布', 'The weather report says it will rain.', '天气预报说会下雨。'],
      ['Unit 5', 'area', '/ˈeəriə/', 'n.', '地域；地区', 'People in this area are kind.', '这个地区的人很友善。'],
      ['Unit 5', 'wood', '/wʊd/', 'n.', '木；木头', 'The chair is made of wood.', '这把椅子是木头做的。'],
      ['Unit 5', 'window', '/ˈwɪndəʊ/', 'n.', '窗；窗户', 'Please close the window.', '请关上窗户。'],
      ['Unit 5', 'flashlight', '/ˈflæʃlaɪt/', 'n.', '手电筒；火炬', 'Take a flashlight with you.', '带上手电筒。'],
      ['Unit 5', 'match', '/mætʃ/', 'n.', '火柴', 'He lit the fire with a match.', '他用火柴点着了火。'],
      ['Unit 5', 'beat', '/biːt/', 'v.', '敲打；打败', 'The rain beat against the window.', '雨敲打着窗户。'],
      ['Unit 5', 'against', '/əˈɡenst/', 'prep.', '倚；碰；撞', 'The bike is against the wall.', '自行车靠在墙上。'],
      ['Unit 5', 'asleep', '/əˈsliːp/', 'adj.', '睡着的', 'The baby is asleep now.', '宝宝现在睡着了。'],
      ['Unit 5', 'rise', '/raɪz/', 'v.', '升起；增加；提高', 'The sun rises in the east.', '太阳从东方升起。'],
      ['Unit 5', 'fallen', '/ˈfɔːlən/', 'adj.', '倒下的；落下的', 'The fallen leaves are everywhere.', '落叶到处都是。'],
      ['Unit 5', 'apart', '/əˈpɑːt/', 'adv.', '分离；分开', 'The old house fell apart.', '老房子散架了。'],
      ['Unit 5', 'icy', '/ˈaɪsi/', 'adj.', '覆盖着冰的；冰冷的', 'The road is icy in winter.', '冬天路面结冰。'],
      ['Unit 5', 'kid', '/kɪd/', 'v.', '开玩笑；欺骗', 'I am just kidding.', '我只是在开玩笑。'],
      ['Unit 5', 'realize', '/ˈriːəlaɪz/', 'v.', '理解；领会；认识到', 'I realized my mistake at last.', '我终于意识到了自己的错误。'],
      ['Unit 5', 'truth', '/truːθ/', 'n.', '实情；事实', 'Please tell me the truth.', '请告诉我真相。'],
      ['Unit 5', 'passage', '/ˈpæsɪdʒ/', 'n.', '章节；段落', 'Read the passage and answer questions.', '阅读短文并回答问题。'],
      ['Unit 5', 'pupil', '/ˈpjuːpl/', 'n.', '学生', 'The pupils are reading in class.', '学生们在课堂上读书。'],
      ['Unit 5', 'completely', '/kəmˈpliːtli/', 'adv.', '彻底地；完全地', 'I completely forgot the time.', '我完全忘记了时间。'],
      ['Unit 5', 'shocked', '/ʃɒkt/', 'adj.', '惊愕的；受震惊的', 'We were shocked at the news.', '我们对这个消息感到震惊。'],
      ['Unit 5', 'silence', '/ˈsaɪləns/', 'n.', '沉默；缄默；无声', 'There was a long silence in the room.', '房间里沉默了很久。'],
      ['Unit 5', 'recently', '/ˈriːsntli/', 'adv.', '不久前；最近', 'I have not seen him recently.', '我最近没见过他。'],
      ['Unit 5', 'date', '/deɪt/', 'n.', '日期；日子', 'What is the date today?', '今天几号？'],
      ['Unit 5', 'tower', '/ˈtaʊə(r)/', 'n.', '塔；塔楼', 'The tower stands on the hill.', '塔矗立在山上。'],
      ['Unit 5', 'fall asleep', '', 'phr.', '进入梦乡；睡着', 'He fell asleep during the film.', '他看电影时睡着了。'],
      ['Unit 5', 'die down', '', 'phr.', '逐渐变弱；逐渐消失', 'The wind died down at night.', '夜里风渐渐小了。'],
      ['Unit 5', 'at first', '', 'phr.', '起初；起先', 'At first, I did not like English.', '起初我不喜欢英语。'],
      // Unit 6 An old man tried to move the mountains.
      ['Unit 6', 'shoot', '/ʃuːt/', 'v.', '射击；发射', 'He shot an arrow at the target.', '他朝靶子射了一箭。'],
      ['Unit 6', 'stone', '/stəʊn/', 'n.', '石头', 'The boy threw a stone into the river.', '男孩把一块石头扔进河里。'],
      ['Unit 6', 'weak', '/wiːk/', 'adj.', '虚弱的；无力的', 'He felt weak after the illness.', '病后他觉得虚弱。'],
      ['Unit 6', 'god', '/ɡɒd/', 'n.', '神；上帝', 'The old story is about a god.', '这个古老的故事讲的是一位神。'],
      ['Unit 6', 'remind', '/rɪˈmaɪnd/', 'v.', '提醒；使想起', 'Please remind me to call her.', '请提醒我给她打电话。'],
      ['Unit 6', 'bit', '/bɪt/', 'n.', '一点；小块', 'There is a bit of water in the cup.', '杯子里有一点水。'],
      ['Unit 6', 'silly', '/ˈsɪli/', 'adj.', '愚蠢的；不明事理的', 'Do not ask silly questions.', '别问傻问题。'],
      ['Unit 6', 'instead of', '', 'phr.', '代替；反而', 'I will have tea instead of coffee.', '我要喝茶，不喝咖啡。'],
      ['Unit 6', 'husband', '/ˈhʌzbənd/', 'n.', '丈夫', 'Her husband is a teacher.', '她的丈夫是老师。'],
      ['Unit 6', 'whole', '/həʊl/', 'adj.', '全部的；整体的', 'It snowed the whole day.', '下了一整天雪。'],
      ['Unit 6', 'scene', '/siːn/', 'n.', '（戏剧或歌剧的）场；场景', 'The play has five scenes.', '这部戏有五场。'],
      ['Unit 6', 'moonlight', '/ˈmuːnlaɪt/', 'n.', '月光', 'The room was bright in the moonlight.', '月光下房间很亮。'],
      ['Unit 6', 'shine', '/ʃaɪn/', 'v.', '发光；照耀', 'The sun shines brightly.', '阳光灿烂。'],
      ['Unit 6', 'bright', '/braɪt/', 'adj.&adv.', '明亮的；光线充足的', 'The moon is bright tonight.', '今晚月亮很亮。'],
      ['Unit 6', 'ground', '/ɡraʊnd/', 'n.', '地；地面', 'There is a bag on the ground.', '地上有一个包。'],
      ['Unit 6', 'lead', '/liːd/', 'v.', '带路；领路', 'The guide led us through the forest.', '向导带我们穿过森林。'],
      ['Unit 6', 'voice', '/vɔɪs/', 'n.', '声音', 'She has a sweet voice.', '她声音甜美。'],
      ['Unit 6', 'brave', '/breɪv/', 'adj.', '勇敢的', 'The brave girl saved her brother.', '勇敢的女孩救了她弟弟。'],
      ['Unit 6', 'prince', '/prɪns/', 'n.', '王子', 'The prince lived in a big castle.', '王子住在一座大城堡里。'],
      ['Unit 6', 'fit', '/fɪt/', 'v.', '适合；合身', 'The shoes fit me well.', '这双鞋我穿很合脚。'],
      ['Unit 6', 'couple', '/ˈkʌpl/', 'n.', '（尤指）夫妻；两人；两件事物', 'The couple have two children.', '这对夫妻有两个孩子。'],
      ['Unit 6', 'smile', '/smaɪl/', 'v.&n.', '笑；微笑', 'She smiled at the baby.', '她对着宝宝微笑。'],
      ['Unit 6', 'marry', '/ˈmæri/', 'v.', '结婚', 'They will marry next year.', '他们明年结婚。'],
      ['Unit 6', 'gold', '/ɡəʊld/', 'n.', '金子；金币', 'The ring is made of gold.', '这枚戒指是金子做的。'],
      ['Unit 6', 'emperor', '/ˈempərə(r)/', 'n.', '皇帝', 'The emperor lived in the palace.', '皇帝住在宫殿里。'],
      ['Unit 6', 'stupid', '/ˈstjuːpɪd/', 'adj.', '愚蠢的', 'It was stupid of me to forget.', '我忘了，真蠢。'],
      ['Unit 6', 'cheat', '/tʃiːt/', 'v.&n.', '欺骗；蒙骗；骗子', 'Do not cheat in the exam.', '考试不要作弊。'],
      ['Unit 6', 'stepmother', '/ˈstepmʌðə(r)/', 'n.', '继母', 'Her stepmother was not kind to her.', '她的继母对她不好。'],
      ['Unit 6', 'wife', '/waɪf/', 'n.', '妻子', 'His wife is a doctor.', '他的妻子是医生。'],
      ['Unit 6', 'magic', '/ˈmædʒɪk/', 'adj.&n.', '有魔力的；魔法', 'The magic stick can talk.', '这根魔杖会说话。'],
      ['Unit 6', 'stick', '/stɪk/', 'n.', '棍；条', 'He picked up a stick to walk.', '他捡起一根棍子走路。'],
      ['Unit 6', 'hide', '/haɪd/', 'v.', '隐藏；隐蔽', 'The cat hid under the bed.', '猫藏在床底下。'],
      ['Unit 6', 'tail', '/teɪl/', 'n.', '尾巴', 'The dog wags its tail.', '狗摇着尾巴。'],
      ['Unit 6', 'western', '/ˈwestən/', 'adj.', '西方国家的；（尤指）欧美的', 'I like western music.', '我喜欢西方音乐。'],
      ['Unit 6', 'excite', '/ɪkˈsaɪt/', 'v.', '使激动；使兴奋', 'The news excited everyone.', '这个消息让大家很兴奋。'],
      // Unit 7 What's the highest mountain in the world?
      ['Unit 7', 'square', '/skweə(r)/', 'n.', '平方；正方形', 'The room is 20 square meters.', '这个房间有20平方米。'],
      ['Unit 7', 'deep', '/diːp/', 'adj.', '深的；纵深的', 'The river is very deep here.', '这条河这里很深。'],
      ['Unit 7', 'desert', '/ˈdezət/', 'n.', '沙漠', 'Camels live in the desert.', '骆驼生活在沙漠里。'],
      ['Unit 7', 'population', '/ˌpɒpjuˈleɪʃn/', 'n.', '人口；人口数量', 'China has a large population.', '中国人口众多。'],
      ['Unit 7', 'Asia', '/ˈeɪʒə/', 'n.', '亚洲', 'China is in Asia.', '中国在亚洲。'],
      ['Unit 7', 'tour', '/tʊə(r)/', 'n.&v.', '旅行；旅游', 'We went on a tour of the city.', '我们游览了这座城市。'],
      ['Unit 7', 'tourist', '/ˈtʊərɪst/', 'n.', '旅行者；观光者', 'Many tourists visit the Great Wall.', '许多游客游览长城。'],
      ['Unit 7', 'wall', '/wɔːl/', 'n.', '墙', 'There is a map on the wall.', '墙上有一张地图。'],
      ['Unit 7', 'ancient', '/ˈeɪnʃənt/', 'adj.', '古代的；古老的', 'Xi an is an ancient city.', '西安是一座古城。'],
      ['Unit 7', 'protect', '/prəˈtekt/', 'v.', '保护；防护', 'We should protect wild animals.', '我们应该保护野生动物。'],
      ['Unit 7', 'wide', '/waɪd/', 'adj.', '宽的；宽阔的', 'The river is very wide.', '这条河很宽。'],
      ['Unit 7', 'achievement', '/əˈtʃiːvmənt/', 'n.', '成就；成绩', 'It was a great achievement.', '这是一项伟大的成就。'],
      ['Unit 7', 'thick', '/θɪk/', 'adj.', '厚的；浓的', 'The book is very thick.', '这本书很厚。'],
      ['Unit 7', 'include', '/ɪnˈkluːd/', 'v.', '包括；包含', 'The price includes breakfast.', '价格包含早餐。'],
      ['Unit 7', 'freezing', '/ˈfriːzɪŋ/', 'adj.', '极冷的；冰冻的', 'It is freezing outside today.', '今天外面冷极了。'],
      ['Unit 7', 'condition', '/kənˈdɪʃn/', 'n.', '条件；状况', 'The road is in good condition.', '这条路状况良好。'],
      ['Unit 7', 'succeed', '/səkˈsiːd/', 'v.', '实现目标；成功', 'He succeeded in passing the exam.', '他成功通过了考试。'],
      ['Unit 7', 'challenge', '/ˈtʃælɪndʒ/', 'n.&v.', '挑战；考验', 'Climbing the mountain is a big challenge.', '爬这座山是个巨大的挑战。'],
      ['Unit 7', 'achieve', '/əˈtʃiːv/', 'v.', '达到；完成；成功', 'Work hard and you will achieve your dream.', '努力你就会实现梦想。'],
      ['Unit 7', 'force', '/fɔːs/', 'n.', '力；力量', 'The force of the wind is strong.', '风力很大。'],
      ['Unit 7', 'nature', '/ˈneɪtʃə(r)/', 'n.', '自然界；大自然', 'We love the beauty of nature.', '我们热爱大自然的美。'],
      ['Unit 7', 'ocean', '/ˈəʊʃn/', 'n.', '大海；海洋', 'The ocean is home to many fish.', '海洋是许多鱼的家园。'],
      ['Unit 7', 'weigh', '/weɪ/', 'v.', '重量是……；称……的重量', 'The baby weighs three kilos.', '这个婴儿重三公斤。'],
      ['Unit 7', 'birth', '/bɜːθ/', 'n.', '出生；诞生', 'The baby was happy at birth.', '宝宝出生时很健康。'],
      ['Unit 7', 'adult', '/ˈædʌlt/', 'n.', '成年人', 'The film is for adults.', '这部电影是给成年人看的。'],
      ['Unit 7', 'bamboo', '/bæmˈbuː/', 'n.', '竹子', 'Pandas eat bamboo.', '熊猫吃竹子。'],
      ['Unit 7', 'endangered', '/ɪnˈdeɪndʒəd/', 'adj.', '濒危的', 'Pandas are endangered animals.', '熊猫是濒危动物。'],
      ['Unit 7', 'research', '/rɪˈsɜːtʃ/', 'n.&v.', '研究；调查', 'Scientists do research on pandas.', '科学家研究熊猫。'],
      ['Unit 7', 'keeper', '/ˈkiːpə(r)/', 'n.', '饲养员；保管人', 'The keeper feeds the animals.', '饲养员喂动物。'],
      ['Unit 7', 'awake', '/əˈweɪk/', 'adj.', '醒着的', 'The baby is still awake.', '宝宝还醒着。'],
      ['Unit 7', 'excitement', '/ɪkˈsaɪtmənt/', 'n.', '激动；兴奋', 'The children shouted with excitement.', '孩子们兴奋地大叫。'],
      ['Unit 7', 'illness', '/ˈɪlnəs/', 'n.', '疾病；病', 'He stayed home because of illness.', '他因病待在家里。'],
      ['Unit 7', 'remaining', '/rɪˈmeɪnɪŋ/', 'adj.', '遗留的；剩余的', 'The remaining food is in the fridge.', '剩下的食物在冰箱里。'],
      ['Unit 7', 'artwork', '/ˈɑːtwɜːk/', 'n.', '艺术品；插图', 'The museum has many artworks.', '博物馆里有许多艺术品。'],
      ['Unit 7', 'wild', '/waɪld/', 'adj.', '野生的', 'These are wild flowers.', '这些是野花。'],
      ['Unit 7', 'government', '/ˈɡʌvənmənt/', 'n.', '政府；内阁', 'The government builds many parks.', '政府建了许多公园。'],
      ['Unit 7', 'whale', '/weɪl/', 'n.', '鲸', 'The whale is a huge animal.', '鲸是巨大的动物。'],
      ['Unit 7', 'oil', '/ɔɪl/', 'n.', '油；食用油；石油', 'Put a little oil in the pan.', '往锅里放一点油。'],
      ['Unit 7', 'protection', '/prəˈtekʃn/', 'n.', '保护；保卫', 'The trees give protection from the sun.', '树木提供遮阳的保护。'],
      ['Unit 7', 'huge', '/hjuːdʒ/', 'adj.', '巨大的；极多的', 'A huge elephant stood by the river.', '一头巨大的大象站在河边。'],
      // Unit 8 Have you read Treasure Island yet?
      ['Unit 8', 'treasure', '/ˈtreʒə(r)/', 'n.', '珠宝；财富', 'They looked for treasure on the island.', '他们在岛上寻找宝藏。'],
      ['Unit 8', 'island', '/ˈaɪlənd/', 'n.', '岛', 'There is a small house on the island.', '岛上有一座小房子。'],
      ['Unit 8', 'classic', '/ˈklæsɪk/', 'n.', '经典作品；名著', 'This book is an English classic.', '这本书是一部英语名著。'],
      ['Unit 8', 'due', '/djuː/', 'adj.', '预期；到期', 'The book is due next week.', '这本书下周到期。'],
      ['Unit 8', 'ship', '/ʃɪp/', 'n.', '船', 'The ship sailed across the sea.', '船驶过大海。'],
      ['Unit 8', 'tool', '/tuːl/', 'n.', '工具', 'A knife is a useful tool.', '刀是有用的工具。'],
      ['Unit 8', 'gun', '/ɡʌn/', 'n.', '枪；炮', 'The man carried a gun.', '那人带着一把枪。'],
      ['Unit 8', 'mark', '/mɑːk/', 'n.', '迹象；记号；分数', 'There are marks on the sand.', '沙滩上有痕迹。'],
      ['Unit 8', 'sand', '/sænd/', 'n.', '沙滩；沙', 'The children play on the sand.', '孩子们在沙滩上玩。'],
      ['Unit 8', 'towards', '/təˈwɔːdz/', 'prep.', '朝；向；对着', 'She walked towards the door.', '她朝门口走去。'],
      ['Unit 8', 'land', '/lænd/', 'n.&v.', '陆地；大地；着陆', 'The plane landed safely.', '飞机安全着陆了。'],
      ['Unit 8', 'fiction', '/ˈfɪkʃn/', 'n.', '小说', 'I like reading science fiction.', '我喜欢读科幻小说。'],
      ['Unit 8', 'technology', '/tekˈnɒlədʒi/', 'n.', '科技；工艺', 'Technology changes our life.', '科技改变我们的生活。'],
      ['Unit 8', 'French', '/frentʃ/', 'n.', '法语', 'She can speak French.', '她会说法语。'],
      ['Unit 8', 'pop', '/pɒp/', 'n.', '流行音乐；流行乐曲', 'Pop music is popular with kids.', '流行音乐很受孩子们欢迎。'],
      ['Unit 8', 'band', '/bænd/', 'n.', '乐队', 'She sings in a school band.', '她在学校乐队唱歌。'],
      ['Unit 8', 'forever', '/fərˈevə(r)/', 'adv.', '永远', 'I will remember you forever.', '我会永远记住你。'],
      ['Unit 8', 'abroad', '/əˈbrɔːd/', 'adv.', '在国外；到国外', 'He wants to study abroad.', '他想出国留学。'],
      ['Unit 8', 'southern', '/ˈsʌðən/', 'adj.', '南方的', 'Guangzhou is in southern China.', '广州在中国南方。'],
      ['Unit 8', 'modern', '/ˈmɒdn/', 'adj.', '现代的；当代的', 'I like modern art.', '我喜欢现代艺术。'],
      ['Unit 8', 'success', '/səkˈses/', 'n.', '成功', 'Hard work brings success.', '努力带来成功。'],
      ['Unit 8', 'belong', '/bɪˈlɒŋ/', 'v.', '属于；归属', 'This book belongs to me.', '这本书是我的。'],
      ['Unit 8', 'laughter', '/ˈlɑːftə(r)/', 'n.', '笑；笑声', 'The room was full of laughter.', '房间里充满了笑声。'],
      ['Unit 8', 'beauty', '/ˈbjuːti/', 'n.', '美；美丽', 'We enjoy the beauty of the lake.', '我们欣赏湖的美景。'],
      ['Unit 8', 'record', '/ˈrekɔːd/', 'n.', '唱片；记录', 'She broke the school record.', '她打破了学校纪录。'],
      ['Unit 8', 'introduce', '/ˌɪntrəˈdjuːs/', 'v.', '介绍；引见', 'Let me introduce my friend to you.', '让我把我的朋友介绍给你。'],
      ['Unit 8', 'line', '/laɪn/', 'n.', '行；排', 'Please read the first line.', '请读第一行。'],
      ['Unit 8', 'hurry', '/ˈhʌri/', 'v.', '匆忙；赶快', 'Hurry up, or we will be late.', '快点，否则我们要迟到了。'],
      ['Unit 8', 'full of', '', 'phr.', '满是……的；充满的', 'The box is full of books.', '箱子里装满了书。'],
      // Unit 9 Have you ever been to a museum?
      ['Unit 9', 'amusement', '/əˈmjuːzmənt/', 'n.', '娱乐；游戏', 'We had fun at the amusement park.', '我们在游乐园玩得很开心。'],
      ['Unit 9', 'somewhere', '/ˈsʌmweə(r)/', 'adv.', '在某处；到某处', 'Let us go somewhere quiet.', '我们去个安静的地方吧。'],
      ['Unit 9', 'camera', '/ˈkæmərə/', 'n.', '照相机；摄影机；摄像机', 'I took a camera on the trip.', '旅行时我带了相机。'],
      ['Unit 9', 'invention', '/ɪnˈvenʃn/', 'n.', '发明；发明物', 'The computer is a great invention.', '电脑是一项伟大的发明。'],
      ['Unit 9', 'invent', '/ɪnˈvent/', 'v.', '发明；创造', 'Who invented the telephone?', '谁发明了电话？'],
      ['Unit 9', 'unbelievable', '/ˌʌnbɪˈliːvəbl/', 'adj.', '难以置信的', 'The story is unbelievable.', '这个故事令人难以置信。'],
      ['Unit 9', 'progress', '/ˈprəʊɡres/', 'n.&v.', '进步；进展', 'She has made great progress in English.', '她的英语进步很大。'],
      ['Unit 9', 'rapid', '/ˈræpɪd/', 'adj.', '迅速的；快速的', 'The city has rapid growth.', '这座城市发展迅速。'],
      ['Unit 9', 'unusual', '/ʌnˈjuːʒuəl/', 'adj.', '特别的；不寻常的', 'It is unusual to snow here.', '这里下雪很不寻常。'],
      ['Unit 9', 'toilet', '/ˈtɔɪlət/', 'n.', '坐便器；厕所', 'The toilet is over there.', '厕所在那边。'],
      ['Unit 9', 'encourage', '/ɪnˈkʌrɪdʒ/', 'v.', '鼓励', 'My teacher encourages me to read more.', '老师鼓励我多读书。'],
      ['Unit 9', 'social', '/ˈsəʊʃl/', 'adj.', '社会的', 'We learn social skills at school.', '我们在学校学习社交技能。'],
      ['Unit 9', 'peaceful', '/ˈpiːsfl/', 'adj.', '和平的；安宁的', 'The village is quiet and peaceful.', '村庄安静祥和。'],
      ['Unit 9', 'performance', '/pəˈfɔːməns/', 'n.', '表演；演出', 'The performance was wonderful.', '演出很精彩。'],
      ['Unit 9', 'perfect', '/ˈpɜːfɪkt/', 'adj.', '完美的；完全的', 'The weather is perfect for a picnic.', '这天气野餐再好不过了。'],
      ['Unit 9', 'itself', '/ɪtˈself/', 'pron.', '它自己', 'The cat washed itself.', '猫给自己清洗。'],
      ['Unit 9', 'collect', '/kəˈlekt/', 'v.', '收集；采集', 'He collects stamps as a hobby.', '他爱好集邮。'],
      ['Unit 9', 'German', '/ˈdʒɜːmən/', 'adj.&n.', '德国的；德语；德国人', 'This car is a German make.', '这辆车是德国制造的。'],
      ['Unit 9', 'theme', '/θiːm/', 'n.', '主题', 'The theme of the book is love.', '这本书的主题是爱。'],
      ['Unit 9', 'ride', '/raɪd/', 'n.', '供乘骑的游乐设施；短途旅程', 'The roller coaster ride is exciting.', '坐过山车很刺激。'],
      ['Unit 9', 'province', '/ˈprɒvɪns/', 'n.', '省份', 'Sichuan is a big province.', '四川是一个大省。'],
      ['Unit 9', 'thousand', '/ˈθaʊznd/', 'num.', '一千', 'There are a thousand students here.', '这里有一千名学生。'],
      ['Unit 9', 'safe', '/seɪf/', 'adj.', '安全的；无危险的', 'It is safe to cross with the green light.', '绿灯过马路很安全。'],
      ['Unit 9', 'simply', '/ˈsɪmpli/', 'adv.', '仅仅；只；不过', 'I simply want to help you.', '我只是想帮你。'],
      ['Unit 9', 'fear', '/fɪə(r)/', 'v.&n.', '害怕；惧怕', 'The little girl fears dogs.', '小女孩怕狗。'],
      ['Unit 9', 'whether', '/ˈweðə(r)/', 'conj.', '不管……（还是）；或者……（或者）', 'I do not know whether he will come.', '我不知道他是否会来。'],
      ['Unit 9', 'mostly', '/ˈməʊstli/', 'adv.', '主要地；通常', 'The students are mostly from China.', '学生大多来自中国。'],
      ['Unit 9', 'fox', '/fɒks/', 'n.', '狐狸', 'The fox has a big tail.', '狐狸有一条大尾巴。'],
      ['Unit 9', 'equator', '/ɪˈkweɪtə(r)/', 'n.', '赤道', 'The equator goes around the earth.', '赤道环绕地球。'],
      ['Unit 9', 'spring', '/sprɪŋ/', 'n.', '春天', 'Flowers come out in spring.', '春天花儿开放。'],
      ['Unit 9', 'location', '/ləʊˈkeɪʃn/', 'n.', '地点；位置', 'The hotel is in a good location.', '酒店位置很好。'],
      ['Unit 9', 'all year round', '', 'phr.', '一年到头；终年', 'It is warm here all year round.', '这里一年到头都很暖和。'],
      // Unit 10 I've had this bike for three years.
      ['Unit 10', 'board', '/bɔːd/', 'n.', '板；木板', 'The board is made of wood.', '这块板是木头做的。'],
      ['Unit 10', 'junior', '/ˈdʒuːniə(r)/', 'adj.', '地位（或职位、级别）低下的', 'He is a junior high school student.', '他是一名初中生。'],
      ['Unit 10', 'bedroom', '/ˈbedruːm/', 'n.', '卧室', 'My bedroom is on the second floor.', '我的卧室在二楼。'],
      ['Unit 10', 'own', '/əʊn/', 'v.', '拥有；有', 'We own a small house.', '我们拥有一座小房子。'],
      ['Unit 10', 'railway', '/ˈreɪlweɪ/', 'n.', '铁路；铁道', 'The railway runs through the city.', '铁路穿过这座城市。'],
      ['Unit 10', 'part', '/pɑːt/', 'v.', '离开；分开', 'We parted at the school gate.', '我们在校门口分开了。'],
      ['Unit 10', 'certain', '/ˈsɜːtn/', 'adj.', '某种；某事；某人', 'A certain Mr. Wang called you.', '有一位王先生给你打过电话。'],
      ['Unit 10', 'honest', '/ˈɒnɪst/', 'adj.', '诚实的；老实的', 'He is an honest boy.', '他是一个诚实的男孩。'],
      ['Unit 10', 'hometown', '/ˈhəʊmtaʊn/', 'n.', '家乡；故乡', 'My hometown is a small village.', '我的家乡是一个小村庄。'],
      ['Unit 10', 'nowadays', '/ˈnaʊədeɪz/', 'adv.', '现今；现在；目前', 'Nowadays people shop online.', '如今人们在网上购物。'],
      ['Unit 10', 'search', '/sɜːtʃ/', 'v.&n.', '搜索；搜查', 'He searched for his key everywhere.', '他到处找他的钥匙。'],
      ['Unit 10', 'among', '/əˈmʌŋ/', 'prep.', '在（其）中；……之一', 'She is the tallest among us.', '她是我们中最高的。'],
      ['Unit 10', 'shame', '/ʃeɪm/', 'n.', '羞耻；羞愧；遗憾', 'It is a shame to waste food.', '浪费食物是可耻的。'],
      ['Unit 10', 'regard', '/rɪˈɡɑːd/', 'v.', '将……认为；把……视为；看待', 'I regard her as my sister.', '我把她当作我的妹妹。'],
      ['Unit 10', 'count', '/kaʊnt/', 'v.', '数数', 'The child can count to one hundred.', '这个孩子能数到一百。'],
      ['Unit 10', 'century', '/ˈsentʃəri/', 'n.', '百年；世纪', 'The castle is five centuries old.', '这座城堡有五个世纪的历史。'],
      ['Unit 10', 'opposite', '/ˈɒpəzɪt/', 'prep.&adj.', '与……相对；在……对面；对面的', 'The bank is opposite the school.', '银行在学校对面。'],
      ['Unit 10', 'especially', '/ɪˈspeʃəli/', 'adv.', '尤其；特别；格外', 'I like music, especially pop.', '我喜欢音乐，尤其是流行音乐。'],
      ['Unit 10', 'childhood', '/ˈtʃaɪldhʊd/', 'n.', '童年；幼年', 'I had a happy childhood.', '我有一个快乐的童年。'],
      ['Unit 10', 'consider', '/kənˈsɪdə(r)/', 'v.', '注视；仔细考虑', 'Please consider my advice.', '请考虑我的建议。'],
      ['Unit 10', 'hold', '/həʊld/', 'v.', '拥有；抓住', 'Hold my hand when we cross.', '过马路时抓住我的手。'],
      ['Unit 10', 'yard sale', '', 'phr.', '庭院拍卖会', 'We sold old things at a yard sale.', '我们在庭院拍卖会上卖旧物。'],
      ['Unit 10', 'check out', '', 'phr.', '察看；观察', 'Check out the new book.', '看看这本新书。'],
      ['Unit 10', 'as for', '', 'phr.', '至于；关于', 'As for me, I like tea.', '至于我，我喜欢茶。'],
      ['Unit 10', 'according to', '', 'phr.', '依据；按照', 'According to the paper, it will rain.', '据报纸说，要下雨了。'],
      ['Unit 10', 'in one s opinion', '', 'phr.', '依……看', 'In my opinion, he is right.', '在我看来，他是对的。'],
    ],
  };
  if (typeof window !== 'undefined') {
    window.VocabSampleBooks = window.VocabSampleBooks || [];
    window.VocabSampleBooks.push(book);
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = book;
})();
